### ISSUE TITLE
How to create a new user / pass auth?

### ISSUE THREAD

**Issue by RANGERBEE** [Joxit/docker-registry-ui#111]
hello @Joxit ,

  How may I create a new user or edit the htpasswd file properly?  Not sure what you refer to about bcrypt.  Simply need to be pointed in the right direction.  :-)

Thank you!

**Comment by RANGERBEE** [comment]
can i use some kind of third party util?  

can i use a stronger hashing algo other than bcrypt?

**Comment by Joxit** [comment]
Hello @RANGERBEE, 

If you want to create a new htpasswd file you can use this command line (on linux). They will ask you to type your password twice. (`-c` for create and `-B` for bcrypt).
```
htpasswd -B -c htpasswd-file username
```
If you need one more user you can use this command line
```
htpasswd -B htpasswd-file username2
```

The command line is available in the package `apache2-utils` for Debian distributions. There are some websites which create htpasswd files too.

Bcrypt is the strongest algo supported by htpasswd. But you can choose between MD5, SHA1, CRYPT and bcrypt.

**Comment by RANGERBEE** [comment]
Excellent, thank you!

**Comment by Joxit** [comment]
You are welcome ☺️
