### ISSUE TITLE
IHM customization

### ISSUE THREAD

**Issue by CircleCode** [Joxit/docker-registry-ui#115]
**Is your feature request related to a problem? Please describe.**
When used in corporate environment, managers are often more interested by the visual aspect than features (as soon as features are okay).
The interface is simple, but does not match corporate colors, etc.

**Describe the solution you'd like**
Adding the possibility to customize
- header
  - color
  - title (`REGISTRY_TITLE` is used in `catalog-header`, but not in page header nor footer)
  - logo
- footer
  - color
  - title (`REGISTRY_TITLE` is used in `catalog-header`, but not in page header nor footer)

this customization coul be achieved by
- using `REGISTRY_TITLE` in header and footer
- using an image from predefined location in the container in the header (this image is then injected through a volume)
- using a custom css from predefined location in the container (this css is then injected through a volume). Note: the css could also fix the image header with no intervention on your side

**Describe alternatives you've considered**
One could fork the project to make these customizations, but it would be sad to create a fork for no feature addition other than a css change

**Additional context**
none

**Comment by Joxit** [comment]
Hi, thank you for your comment.

I'm glad that you are using my project in a corporate environment :smile:.
I chose neutral colors so that the interface could satisfy everyone. Anyway, changing the header/footer colors is a good idea :thinking: 

The footer content will not change, it's an Open-Source project under AGPLv3, and I don't want to add a way to remove credits for the project :slightly_smiling_face:.

**Comment by CircleCode** [comment]
Hi, thanks for the quick reply

> I'm glad that you are using my project in a corporate environment :smile: .

Thanks for the tool, it is becoming the de facto companion of our internal private registry.

> I chose neutral colors so that the interface could satisfy everyone.

And this is good this way. If you rejected this feature request, we would probably keep it as is.

> Anyway, changing the header/footer colors is a good idea :thinking: 

Do you have an idea of the way you could propose this feature?

> The footer content will not change, it's an Open-Source project under AGPLv3, and I don't want to add a way to remove credits for the project slightly_smiling_face.

Working myself on an open source project, I understand it, and I am sorry if it seems i wanted to remove credits. Maybe it can be crystal clear if the footer says: _powered by Docker Registry UI v1.4.0_, making it obvious this is the name of the tool, and not the title of the page (It appeared so because it was the same text as the header, and I misinterpreted it)

**Comment by Joxit** [comment]
> Do you have an idea of the way you could propose this feature?

I think I will add some environment variables (again).

> Maybe it can be crystal clear if the footer says: powered by Docker Registry UI v1.4.0

The Powered By is usually used to print the name of a brand/company not the product itself ? :thinking: but this could be a solution :slightly_smiling_face:

**Comment by bc-vivek** [comment]
@Joxit  I am using your project , and the issue I faced as after going to docker-registry ui , we are not getting any button to log out.
I am not sure how to do this, Please let me know if there is any way to go it.

**Comment by CircleCode** [comment]
> I think I will add some environment variables (again).

Isn't it easier to allow a css to be mounted somewhere in the image, and loaded additionally to the current one (you would provide a default css with default colors, and the mounted one would overwrite it)?
It would allow much more customization (like logo, font, etc.) without requiring variables and further work on your side

> The Powered By is usually used to print the name of a brand/company not the product itself ? thinking but this could be a solution slightly_smiling_face

Maybe then *site generated with Docker Registry UI v1.4.0*

**Comment by Joxit** [comment]
Hi there, happy new year and good news for all of you, dark mode is coming !
Please checkout https://github.com/Joxit/docker-registry-ui/pull/283, you can give me feedback if you want :smile:
