### ISSUE TITLE
reduce http  api calls when using Basic Auth?

### ISSUE THREAD

**Issue by cr1st1p** [Joxit/docker-registry-ui#117]
**Is your feature request related to a problem? Please describe.**
If the repository is protected by Basic Http authorization, the number of calls being done by the browser is double. I.e. it does a normal unauthenticated call. just to get the authorization error and then it does the authorized call. And this happen for each and every one of the api calls.

Is it possible for the code to check if the repo looks to be protected, to always force authorization headers?

**Describe the solution you'd like**
After discovering that the repository is protected by a Basic Auth scheme, code should try to always add the auth headers and not wait for the browser to ask for them (or whatever implementation is).
It would reduce the number of api calls by 2.

**Comment by Joxit** [comment]
Hi,

Thank you for your feature request :+1: I think this feature will not be available on `DELETE` queries :thinking:.

**Comment by Joxit** [comment]
Done with `REGISTRY_SECURED`
