### ISSUE TITLE
DELETE on Registry with Basic Auth not working

### ISSUE THREAD

**Issue by mabaum** [Joxit/docker-registry-ui#118]
Hi, I use this docker registry UI and I have an issue...

## Bug description

I have set up a Registry which requires Basic Auth. The Registry lists all Images and Tags correctly.
When i Click on "Delete" within the UI an error "Access on registry response was blocked. Try adding the header `Access-Control-Expose-Headers: Docker-Content-Digest` to your proxy or registry: https://docs.docker.com/registry/configuration/#http" is displayed but on the Console u can see that there is an 401 delivered back to the UI from the registry

## How to Reproduce

1. Log into a Registry secured by Basic Auth
2. Click on 'Delete' on any Image
3. Error is displayed

## Expected behavior

Successful delete (maybe a Basic auth Dialog from Browser before)

## System information
 
- OS: Macos

- Browser:
    - Name:  Chrome 
    - Version: Version 81.0.4028.0 (Official Build) canary (64-bit)
- Docker registry UI:
    - Version: 1.4.3
    - Interface variant: latest and static
    - Server: docker

    - Docker version: 19.03
    - OS/Arch: linux/amd64
    - Tools: docker-compose

**Comment by Joxit** [comment]
Hi

is your issue related to #104 ? The registry is buggy, it returns 401 status codes on `OPTIONS` for `DELETE` requests and that's not how to do it... The full explanation [here](https://github.com/Joxit/docker-registry-ui/issues/104#issuecomment-538633095).

**Comment by mabaum** [comment]
yes was #104 

https://enable-cors.org/server_nginx.html did the part with the OPTIONS header within my nginx - config :)

**Comment by Joxit** [comment]
Okay, that's great ! :smile: I close this
