### ISSUE TITLE
Allow sorting of tags by creation date

### ISSUE THREAD

**Issue by yanickgirouard** [Joxit/docker-registry-ui#125]
The Creation Date column is not sortable and shows the date as a relative date string (x y ago) and you have to hover the date to see the full datetime.

It would be very helpful to be able to list tags by creation date so we can more easily delete old tags by age, for example.

**Comment by Joxit** [comment]
Sorting tags by creation date can't be done because of pagination.
If I do a `Sort by date`, it will sort only the current page (100 first tags) and this will not be intuitive.

**Comment by nicko7i** [comment]
Isn't that true for Tag column as well?  And equally un-intuitive?

I get that you are sorting on the browser side and you don't have control of the server.  Presumably the server API doesn't support sorting on the server side before pagination.

I agree with the OP that sorting on creation date is extremely useful.

Perhaps, when there are more than 100 entries, a note could be displayed underneath the paginator.  Something like:  "Pages are sorted by ascending tag.  Within each page, entries may be sorted by Tag, Size and Creation Date".

**Comment by Joxit** [comment]
> Perhaps, when there are more than 100 entries, a note could be displayed underneath the paginator. Something like: "Pages are sorted by ascending tag. Within each page, entries may be sorted by Tag, Size or Creation Date".

Yes, I think this is definitely the right thing to do !

**Comment by Gelob** [comment]
I'd like to be able to sort by Size as well, even if its only the current page.

**Comment by Joxit** [comment]
Will be release in 2.0.0 :rocket:
