### ISSUE TITLE
Hide SHA-Hash column

### ISSUE THREAD

**Issue by Herr-Sepp** [Joxit/docker-registry-ui#126]
Hi thanks for your great UI.

On your gif the column for the sha-hash is hidden and if i understand it correctly it will only show if i hover over with the cursor.

![image](https://user-images.githubusercontent.com/10489458/77167771-f37eff80-6ab6-11ea-8274-7b056f55f1f1.png)

But on my instance and even the [demo](https://joxit.dev/docker-registry-ui/demo/?page=1#!taglist/alpine) the column is always shown and makes the table difficult to read because the rows are so wide.
![image](https://user-images.githubusercontent.com/10489458/77167715-cfbbb980-6ab6-11ea-88cc-a84d7c9feb79.png)

Is this a bug or how can I achieve to hide the sha-column by default?

**Comment by Joxit** [comment]
Hi

Sorry, this is not a bug, the gif was made at version 1.3.0 and the latest UI version is 1.4.8...
The feature has been added in 1.4.0 with #102 
We did some tests with different windows sizes and the digest should be hidden at 710px.

I should update the GIF :sweat_smile:

**Comment by Herr-Sepp** [comment]
Any chance to give us a flag or something to hide this column?
I dont need it and when a tag is rellay long, i got a scrollbar on the bottom of the table even on big screens.

**Comment by Joxit** [comment]
Hum... Yes I think it's possible

What is the spec of your screen ? In px ? Retina supported ?

**Comment by Herr-Sepp** [comment]
![image](https://user-images.githubusercontent.com/10489458/77254808-96747c80-6c63-11ea-87e7-524d7a436863.png)


27" 2560X1440 (windows scaling 100%) 

But this happens on any screen, because the table will be wider then the hard limit of 1440px with Content Digest and Tag column.

**Comment by Joxit** [comment]
Oh! Ok, this is because the tag name is longer than expected ! I understand, thanks for the intel :slightly_smiling_face:

**Comment by Joxit** [comment]
Hi @Herr-Sepp, I did a PR for this issue, you can hide the digest with `SHOW_CONTENT_DIGEST=false`.
But I also fixed the digest length when a tag is too long :smile:
