### ISSUE TITLE
Can't delete image

### ISSUE THREAD

**Issue by winmasta** [Joxit/docker-registry-ui#133]
Hi, I use this docker registry UI and I have an issue...

## Bug description

docker container was ran as mentioned with option DELETE_IMAGES=true
but image can't be deleted

## How to Reproduce

```
docker network create registry-ui-net
docker run -d --net registry-ui-net --name registry-srv registry:2
docker run -d --net registry-ui-net -p 80:80 -e REGISTRY_URL=http://registry-srv:5000 -e DELETE_IMAGES=true -e REGISTRY_TITLE="My registry" --name registry-ui joxit/docker-registry-ui:static
docker pull ubuntu:16.04
docker tag ubuntu:16.04 localhost/my-ubuntu
docker push localhost/my-ubuntu
```

Go to docker registry web interface and try to delete image by pushig on trash icon

## Expected behavior

Image should be deleted

## Screenshots

![изображение](https://user-images.githubusercontent.com/29568484/83538546-25352d80-a520-11ea-9ce5-1fd64e39d05b.png)

## System information

- OS: Ubuntu 20.04 server
- Docker registry UI:
    - Version: [e.g. 1.4.9]
    - Server: [docker]

    - Docker version: [e.g. 19.03.11]
    - Docker registry ui tag: [static]
    - OS/Arch: [linux/amd64]

**Comment by winmasta** [comment]
### Additional Context

`winmasta@docker-registry:~$ docker exec -it registry-ui /bin/ash
/usr/share/nginx/html # echo $DELETE_IMAGES
true
`

`winmasta@docker-registry:~$ docker logs registry-ui 
192.168.8.50 - - [02/Jun/2020:15:21:13 +0000] "GET /?page=1 HTTP/1.1" 200 1376 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
192.168.8.50 - - [02/Jun/2020:15:21:13 +0000] "GET /vendor.css HTTP/1.1" 200 27015 "http://192.168.8.28/?page=1" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
192.168.8.50 - - [02/Jun/2020:15:21:13 +0000] "GET /style.css HTTP/1.1" 200 10024 "http://192.168.8.28/?page=1" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
192.168.8.50 - - [02/Jun/2020:15:21:13 +0000] "GET /scripts/vendor.js HTTP/1.1" 200 53205 "http://192.168.8.28/?page=1" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
192.168.8.50 - - [02/Jun/2020:15:21:13 +0000] "GET /scripts/docker-registry-ui.js HTTP/1.1" 200 28376 "http://192.168.8.28/?page=1" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
192.168.8.50 - - [02/Jun/2020:15:21:14 +0000] "GET /v2/my-ubuntu/tags/list HTTP/1.1" 200 39 "http://192.168.8.28/?page=1" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
192.168.8.50 - - [02/Jun/2020:15:21:14 +0000] "GET /fonts/MaterialIcons-Regular.woff2 HTTP/1.1" 200 55208 "http://192.168.8.28/style.css" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
192.168.8.50 - - [02/Jun/2020:15:21:14 +0000] "GET /v2/my-ubuntu/manifests/latest HTTP/1.1" 200 1150 "http://192.168.8.28/?page=1" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
192.168.8.50 - - [02/Jun/2020:15:21:14 +0000] "GET /v2/my-ubuntu/blobs/sha256:005d2078bdfab5066ae941cea93f644f5fd25521849c870f4e1496f4526d1d5b HTTP/1.1" 200 3401 "http://192.168.8.28/?page=1" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
2020/06/02 15:21:14 [error] 56#56: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.8.50, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.8.28"
192.168.8.50 - - [02/Jun/2020:15:21:14 +0000] "GET /favicon.ico HTTP/1.1" 404 154 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
192.168.8.50 - - [02/Jun/2020:15:21:15 +0000] "DELETE /v2/my-ubuntu/manifests/sha256:a4fc0c40360ff2224db3a483e5d80e9164fe3fdce2a8439d2686270643974632 HTTP/1.1" 405 78 "http://192.168.8.28/?page=1" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
`

**Comment by Joxit** [comment]
Hello, thank you for your issue and for using this project :smile: 

To enable delete, you must provide a custom configuration for your registry server (see https://github.com/Joxit/docker-registry-ui#using-delete)

```yml
storage:
  delete:
    enabled: true
http:
  headers:
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
```

**Comment by winmasta** [comment]
Thank you very much, it works, sorry for my inattention, thanks for your project

**Comment by okutasan** [comment]
i has add that to my config, but still cant delete the images :cry: . 
my config 
`http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['my_url']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization','Accept']
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
`

**Comment by Joxit** [comment]
Hello @okutasan, thank you for using my project
Please open a new issue with all the required information (full config, versions used, docker-compose etc)
