### ISSUE TITLE
Access-Control-Allow-Origin not working

### ISSUE THREAD

**Issue by Hamsterman** [Joxit/docker-registry-ui#136]
I have a Registry running and I have started the UI like this:

docker run -d --name RegistryUI -p 8008:80 -e URL=https://mylocalregistry.domain.com -e DELETE_IMAGES=true -e REGISTRY_TITLE="My Registry" joxit/docker-registry-ui:static

I get this error:

An error occured: Check your connection and your registry must have `Access-Control-Allow-Origin` header set to `http://UI-URL:PORT`

The registry is open and require no credentials.

I tried adding:
-e REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin="*"
to the Registry.

I get this error:
configuration error: error parsing /etc/docker/registry/config.yml: yaml: did not find expected alphabetic or numeric character

**Comment by g41n** [comment]
May be related to #104 ?

**Comment by Joxit** [comment]
Hi @Hamsterman , try with `-e REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin='["*"]'` use an array instead of standalone stars.

**Comment by Hamsterman** [comment]
Hi @Joxit - Sorry that did not help. Same error

**Comment by Joxit** [comment]
Close the issue due to inactivity

**Comment by gamosoft** [comment]
Hello there, I'm having exactly that same issue and I *think* it may be due to the image used?

If I try the sample files with this image:
**joxit/docker-registry-ui:1.5-static**

it all works fine, but if I try with the latest (?)
**joxit/docker-registry-ui:2.3.2**

then I keep getting the error as specified in the OP.

Thank you.

**Comment by Joxit** [comment]
Hi @gamosoft, thank you for using my project.

Please open a new PR using bug report template with all required information (docker-compose, configuration, browser, etc).
