### ISSUE TITLE
Server not found after click on image name

### ISSUE THREAD

**Issue by kmadac** [Joxit/docker-registry-ui#137]
Hi, I use this docker registry UI and I have an issue...

## Bug description
I have a docker registry UI running from docker image 

joxit/docker-registry-ui   latest              93daded3b6d9        40 hours ago        22MB

URL of my own docker registry is https://myregistry.com/ and URL of UI is https://myregistry.com/ui
Registry has basic auth configured and both are behind reverse proxy . When I browse to https://myregistry.com/ui I can see the list of images, but when I click on image name I got Server Not Found error and no tags are shown. But when I refresh the page with F5, tags are correctly shown.
Web console in browser shows that after clicking the UI is trying to reach docker registry api on https://myregistry.com/ui/v2/imagename/tags/list but when I refresh the page UI goes correctly to https://myregistry.com/v2/imagename/tags/list.

## How to Reproduce

See description above.

My docker registry ui docker configuration:
```
docker run -d -p 80:80 -e REGISTRY_URL=https://myregistry.com/ -e REGISTRY_TITLE="My Registry" joxit/docker-registry-ui
```

My private docker registry configuration
```
docker run -v "$(pwd)"/auth:/auth -d -p 5000:5000 --name registry -e REGISTRY_AUTH=htpasswd -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd registry:2
```

I have trafik reverse proxy in front of them.

## Expected behavior

Clicking on image name would show image tags.

## Screenshots

![Screenshot from 2020-06-23 16-36-28](https://user-images.githubusercontent.com/3167253/85417360-ca678280-b56f-11ea-972a-85a6257c57b0.png)

![Screenshot from 2020-06-23 16-36-43](https://user-images.githubusercontent.com/3167253/85417349-c9365580-b56f-11ea-9c96-1ed16933a399.png)

## System information

OS: Ubuntu 18.04
- Browser:
    - Name:  Firefox
    - Version: 77.0.1
- Docker registry UI:
    - Version: 1.5.0
    - Server: Ubuntu 18.04
    - Docker version: 19.03.6
    - Docker registry ui tag: latest
    - OS/Arch:linux/amd64
    - Tools: docker

**Comment by Joxit** [comment]
Hello @kmadac,
Thank you for your issue and using this project :) 
With your configuration, you must use the `static` tag instead of `latest`. `static` is a UI for a single registry, the `latest` tag is for many registries and sharing (for example http://joxit.dev/docker-registry-ui/demo/?url=https://myregistry.com).

I suggest you the environment `URL` instead of `REGISTRY_URL`.
`REGISTRY_URL` is when the UI is used as a proxy (avoid CORS errors) and `URL` for common usage.

**Comment by Joxit** [comment]
Close the issue due to inactivity
