### ISSUE TITLE
Unable to disable delete images in static interface

### ISSUE THREAD

**Issue by hapatrick** [Joxit/docker-registry-ui#142]
Hi, I use this docker registry UI and I have an issue...

## Bug description

Documentation says the running with "-e DELETE_IMAGES=false" should disable deleting images. However, when I do this the "delete image" button still shows up and still works.

Digging deeper, I found that the entrypoint script modifies scripts/docker-registry-ui.js if DELETE_IMAGES is false, but not scripts/docker-registry-ui-static.js. But even making the same modification in scripts/docker-registry-ui-static.js, the "delete image" button is still present.

## How to Reproduce

Start container like this:

docker run -d \
    -p 80:80\
    --name registry-ui \
    --restart=always \
    -e REGISTRY_URL=http://some-hostname:5000 \
    -e DELETE_IMAGES=false \
    -e REGISTRY_TITLE=some-title \
    joxit/docker-registry-ui:static

Go to the UI in a web browser.

Try to delete an image...it works.

## Expected behavior

I would expect that either the "delete image" button is not shown, or it does not work.

## Screenshots

N/A

## System information

N/A

## Additional context

N/A

**Comment by Joxit** [comment]
Hi, thank you for your issue. I'm sorry, I can't reproduce your issue :confused: 

I used your command

```sh
docker pull joxit/docker-registry-ui:static
docker run -ti --rm -p 80:80 --name registry-ui  -e REGISTRY_URL=http://some-hostname:5000 -e DELETE_IMAGES=false -e REGISTRY_TITLE=some-title joxit/docker-registry-ui:static
```

And I do not have the delete button.... :man_shrugging:

**Comment by Joxit** [comment]
Anyway, when the environment variable is not present, the delete feature is also disable.

**Comment by hapatrick** [comment]
Just to make sure I'm not being dense, this is the delete button we're talking about right? The trashcan icon?
![image](https://user-images.githubusercontent.com/25060759/88805484-35166a00-d17d-11ea-8652-8bf83f4a7ca9.png)

I tried deleting the image and pulling it again, tried with DELETE_IMAGES=false and without specifying the environment variable, and that button still shows up. Not sure what I'm doing wrong.

Thanks for looking at it.

**Comment by hapatrick** [comment]
I figured it out. It was my browser's cache. The first time I ran the container I had DELETE_IMAGES=true. When I restarted with DELETE_IMAGES=false, my browser kept using a cached version of the js file, even though I refreshed. After I cleared the cache, the delete button disappeared.

So it was user error, it works as it should. Closing this.
