### ISSUE TITLE
Token authentication

### ISSUE THREAD

**Issue by igoras1993** [Joxit/docker-registry-ui#143]
**Is your feature request related to a problem? Please describe.**
In Docker registry V2, a preferred way to authenticate is using a Central Auth architecture. This is described [here](https://docs.docker.com/registry/spec/auth/token/). An authorization protocol is actually simple and straight forward:
1. Perform ordinary request to docker registry
2. If getting `401` response code, look for `WWW-Authenticate` header, extracting `realm` and `scope` parameters.
3. Perform a `GET` request:
    3.1. Use address given in `realm`, 
    3.2. Send `scope` along with parameters,
    3.3. Use Basic Authentication to pass username and password
4. Obtain `token` from the response
5. Resend original request to docker registry, but this time place obtained token in `Authentication: Bearer <...>` header.
6. If given token authorizes client to a given resource, docker registry will return correct response.

This is a very general and powerful way for doing authentication. It strongly separates registry app from the auth part. Client's responsibility is only to follow protocol and supply `username` and `password` in 3.3. step.

Would You mind to implement this kind of protocol in Your UI project?

**Describe the solution you'd like**
Actually, the simplest algorithm I can imagine will look like this:
1. Every time experiencing 401 from DR, display a login form for user
2. Follow step 3. from authentication protocol
3. Use obtained token in `Authentication: Bearer <...>` header in future requests.

**Describe alternatives you've considered**
A more general way involves playing with refresh tokens, which of course is also possible.

**Comment by Joxit** [comment]
Hello,

Thank you for your feature request :) I'm supporting only basic auth because it was the easiest way.
Token authentication can be interesting, so I try to do something but there will be no guarantee

**Comment by Joxit** [comment]
Will be release in 2.0.0 :rocket:

**Comment by Cronist** [comment]
I am one of the guys waiting for token auth released for UI too. still pending.
