### ISSUE TITLE
recommend stylesheet directly build in code

### ISSUE THREAD

**Issue by xfduan** [Joxit/docker-registry-ui#145]
load failed.
https://fonts.googleapis.com/css?family=Roboto+Mono|Roboto:300,400,700&display=swap

**Comment by Joxit** [comment]
This is a CDN for Roboto font. Are you in China ? Google Font API is not available ?

**Comment by xfduan** [comment]
Yes. This font i saw it's size is not large, then i recomend directly build in code. 
When i deloy this project, because of network situation, i can't open page because of this font load failed.

**Comment by Joxit** [comment]
You are now in my [contributors list](https://github.com/Joxit/docker-registry-ui/blob/master/CONTRIBUTORS.md) :smile:
