### ISSUE TITLE
UI User and Passwd via Helm Chart

### ISSUE THREAD

**Issue by haeussler247** [Joxit/docker-registry-ui#148]
Hi @Joxit,

is there a possibility to add a user and passwd via the helm chart for the ui?
I'm just seeing the httpasswd option for the registry part, but not for the ui.

Am I missing something?

Best Regards

**Comment by Joxit** [comment]
Hi @haeussler247,

The UI do not have user/password configuration because the registry configuration should be enough.
When you are using the UI from your browser, you will ask access to you private registry (with your registry user/password).
If you do not have the correct credentials, the UI will show an error and your images will not be available.

**Comment by haeussler247** [comment]
Hi @Joxit,

I was Not asked to enter My creds when i accessed the registry via the Browser. But when i want to Push or pull i have to Login First.
Since i dont have  to login for the Web Interface, everyone can view and delete My images.

Like i Said i just added the secrets:httpasswd attribute to the registry part within the helm Chart. And i Never entered them in the web...

**Comment by Joxit** [comment]
Hum... I'm sorry, I'm not familiar with Helm and k8s, this example was a kind contribution by @sebt3 

I've deployed a [`UI as standalone`](https://github.com/Joxit/docker-registry-ui/tree/master/examples/ui-as-standalone) (using docker compose examples) instance just to understand what you are looking for. Here is the instance : https://registry-ui.joxit.dev/. This is what you want ? (Credentials are `registry:ui`)

As I said, there is no built-in configuration to add credential to the Web Interface. Only the registry itself can be secured. As you can see in my example, the Web Interface is available without credentials, but you can't see/delete my images without login first to the registry (just like docker CLI). This is what I wanted to explain to you earlier.

So this is odd, if you've added something like
https://github.com/Joxit/docker-registry-ui/blob/1220825f31ccce38f0c54254b38456e3df792e03/examples/ui-as-standalone/registry-config/credentials.yml#L22-L25

In your Helm [`reg-configmap.yaml`](https://github.com/Joxit/docker-registry-ui/blob/1220825f31ccce38f0c54254b38456e3df792e03/examples/helm/docker-registry-ui/templates/reg-configmap.yaml#L28-L31) file, you should have the same workflow as mine...

----

FYI, there are two way to use the UI:
1. [UI as proxy](https://github.com/Joxit/docker-registry-ui/tree/master/examples/ui-as-proxy) when we use the environment variable `REGISTRY_URL`
2. [UI as standalone](https://github.com/Joxit/docker-registry-ui/tree/master/examples/ui-as-standalone) when we use the environment variable `URL`

I read the full Helm [configuration](https://github.com/Joxit/docker-registry-ui/tree/d7a19734ce52a05ae4e6cfe2dcefaba34a448ea6/examples/helm/docker-registry-ui#configuration) and code.

You can find the same in the Helm UI deployment here and when you use in your helm configuration `ui.proxy` and `registry.url`
https://github.com/Joxit/docker-registry-ui/blob/d7a19734ce52a05ae4e6cfe2dcefaba34a448ea6/examples/helm/docker-registry-ui/templates/ui-deployment.yaml#L30-L31

When `ui.proxy` is true, when you will access the UI, it will be used as a proxy to you registry. This means, if your credential configuration is not done by your registry itself but by a reverse proxy, the UI will bypass this step... So you will not need creds when you will access the registry.

When `ui.proxy` is false, you will need to write your external registry URL in `registry.url`. In this case, when you will access to the registry, you will use the conventional way... The same as your docker API (so with credentials etc).

Hope this helps...

**Comment by haeussler247** [comment]
Ok perfect, 
I think I know what you are talking now.
So I'm using the UI as a proxy.
So your example is exactly what I want, but I want to use "your" provided registry, not a "self-hosted" one.

I added the auth parameters to my ConfigMap:

`    auth:
      htpasswd:
        realm: basic-realm
        path: /etc/docker/registry/htpasswd`

and in my values.yaml:
registry:
  volumes:
    - ./registry-config/htpasswd:/etc/docker/registry/htpasswd

Now I'm getting following error:

`panic: unable to configure authorization (htpasswd): failed to open htpasswd path open /etc/docker/registry/htpasswd: read-only file system `

Did I forget a config value?

**Comment by Joxit** [comment]
Nice :smile: 

Hum... Your error means that your registry is looking for the file `/etc/docker/registry/htpasswd` but the file does not exists AND is on a read-only filesystem.

This may be a kubernetes or Helm volume configuration. Maybe `registry.persistence.enabled` ?
Your file on your filesystem `./registry-config/htpasswd` does exists ? IDK if `volumes` is really used for volume binding... Or if you should use `resources` ? Or maybe we can't add a custom `htpasswd` ?

I found the volume configuration here:
https://github.com/Joxit/docker-registry-ui/blob/1220825f31ccce38f0c54254b38456e3df792e03/examples/helm/docker-registry-ui/templates/reg-deployment.yaml#L42-L46

and here:
https://github.com/Joxit/docker-registry-ui/blob/1220825f31ccce38f0c54254b38456e3df792e03/examples/helm/docker-registry-ui/templates/reg-deployment.yaml#L22-L33

Maybe you should also update the [configMap](https://github.com/Joxit/docker-registry-ui/blob/master/examples/helm/docker-registry-ui/templates/reg-configmap.yaml) file and the content of your `htpasswd` :thinking: 

Sorry again, I'm not a Helm user :sweat_smile:

**Comment by haeussler247** [comment]
Hey,

I think I did the next step.
Now I see the correct config.yml and the Htpasswd file in my docker container, and the content is also correct.

I'm just not sure about the  `realm` attribute in the auth parameter. What key do I have to enter there?
`basic-realm` is just a placeholder I would assume?

If I try `basic-realm` or any other key, I get the error message:

`time="2020-10-19T08:34:45.539442422Z" level=warning msg="error authorizing context: basic authentication challenge for realm "basic-realm": invalid authorization credential"`

This error message is from my registry docker container.
This part confuses me.
Why is my registry trying to check the credentials? And against which values?
In my Htpasswd file are the creds defined, but I didn't enter some.

What am I missing?

**Comment by Joxit** [comment]
On [docker registry htpasswd doc](https://docs.docker.com/registry/configuration/#htpasswd) there are : 
> The htpasswd authentication backed allows you to configure basic authentication using an Apache htpasswd file. The only supported password format is [**bcrypt**](http://en.wikipedia.org/wiki/Bcrypt). Entries with other hash types are ignored. The htpasswd file is loaded once, at startup. If the file is invalid, the registry will display an error and will not start.
> **Warning**: If the htpasswd file is missing, the file will be created and provisioned with a default user and automatically generated password. The password will be printed to stdout.
>
>Parameter | Required | Description
>-- | -- | --
>realm | yes | The realm in which the registry server authenticates.
>path | yes | The path to the htpasswd file to load at startup.

1. Now I understand why the registry server fail at start-up on read only filesystem when the htpasswd file is missing :sweat_smile: 
2. realm is required, but no info on what the value should be :shrug:... In their example the value is `basic-realm`, just like you. Since you are using `htpasswd`, every endpoint of your registry will be secured via basic authentication.
3. Only users in your `htpasswd` will be granted to use your registry. If you file is empty, no one will access to your registry.
4. If you are using your registry via curl, use the option `--user login:password`.
5. You **MUST** use bcrypt algorithm for your passwords in your `htpasswd` file. Because the docker registry is compatible only with bcrypt.

**Comment by Joxit** [comment]
Hi @haeussler247, can I close this issue ?

**Comment by haeussler247** [comment]
Hey,

I got it running, but I had to disable the probe section. So I turned liveness and readiness of (false). After that everything was running smoothly and as expected. So yeah, theoretically you can close this issue.

**Comment by Joxit** [comment]
Yeah! Ok thx :smile:
