### ISSUE TITLE
Google fonts should be packaged in the application

### ISSUE THREAD

**Issue by pidario** [Joxit/docker-registry-ui#149]
Sometimes registries are deployed in an air-gapped server, with no internet connection.

This causes the ui to stop rendering until the request ends with an error.
It could be easily solved by packaging fonts inside the app, or if you don't feel like it, by using the rel preload function of html5.

**Comment by Joxit** [comment]
Hi, thank you for your issue. I will include fonts in the project.

related #145

**Comment by pidario** [comment]
Good to hear! And apologies for the double issue, I guess my search wasn't thorough enough.

**Comment by Joxit** [comment]
Don't worry, the previous issue was closed (and not obvious :sweat_smile:)

**Comment by Joxit** [comment]
You are now in my [contributors list](https://github.com/Joxit/docker-registry-ui/blob/master/CONTRIBUTORS.md) :smile:

**Comment by pidario** [comment]
> You are now in my [contributors list](https://github.com/Joxit/docker-registry-ui/blob/master/CONTRIBUTORS.md) 😄

I was already there 😉 now there's two pidario

**Comment by Joxit** [comment]
Ha ha ha you're right 😂
