### ISSUE TITLE
Is it possible to add basic documentation for images?

### ISSUE THREAD

**Issue by cmhh** [Joxit/docker-registry-ui#156]
Would it be possible to add basic documentation for images?  Not as comprehensive as you get on dockerhub, for example, but at least the ability to add a few `docker run ...` examples, and list the available / expected environment variables.  

I realise this is not supported by the Docker Registry API itself, and isn't really consistent with the design of this UI (the information would probably have to be editable content within the UI itself, and then persisted somehow), but it would be a useful addition.

**Comment by Joxit** [comment]
A basic documentation of your images from your private registry inside the Docker Registry UI ? No, this is not possible. The UI is a stateless webpage using the Docker Registry API, so I can't add this kind of feature :(.

However, you can still know the environment variables that are used in the image by looking at the history :shrug:.

**Comment by cmhh** [comment]
Thanks.  I assumed given your UI was deliberately stateless that it would be unlikely, but thought I'd ask.  It would be cool if this was added as an optional field directly to the registry API, I guess.

**Comment by DiegoSpinola** [comment]
@cmhh you could use #240 to achieve something like that, I'm looking to do the same but with a link to a readme file...

**Comment by Joxit** [comment]
@DiegoSpinola what do you mean by a link to a readme? You are storing the url of the readme in a label? And you want to transform this url as text into a real link?
