### ISSUE TITLE
Provide direct link to an image (with and without tag)

### ISSUE THREAD

**Issue by FSMaxB-dooshop** [Joxit/docker-registry-ui#158]
I want to be able to create links to the overview page of an image and specific tagged images, but as far as I can see, it isn't possible to create a direct link to it because the URL always contains the `page` query parameter.

My use case is to automatically send a slack message with a link to the image after building it.

**Comment by Joxit** [comment]
Hi there,

You want a link to the tag list page ? (like [this one](https://joxit.dev/docker-registry-ui/demo/?url=https%3A%2F%2Fraw.githubusercontent.com%2FJoxit%2Fdocker-registry-ui%2Fmaster%2Fdemo&page=1#!taglist/alpine)) The template is `http://ui.registry.example.com/#!taglist/{image name}`
Or the history of the built image ? (like [this one](https://joxit.dev/docker-registry-ui/demo/?url=https%3A%2F%2Fraw.githubusercontent.com%2FJoxit%2Fdocker-registry-ui%2Fmaster%2Fdemo&page=1#!taghistory/image/alpine/tag/latest) but no longer works on github) `http://ui.registry.example.com#!taghistory/image/{image name}/tag/{tag name}`

**Comment by FSMaxB-dooshop** [comment]
Both of that is exactly what I was looking for. Didn't realise these work without specifying the page, thanks a lot.
