### ISSUE TITLE
expose some labels

### ISSUE THREAD

**Issue by CircleCode** [Joxit/docker-registry-ui#160]
In our company, this is used as a browser for the images we build.
These images have metadata in custom labels, and we'd love to expose those labels directly on the UI when displaying information for a given tag.
is this at least possible, and would it be something you'd consider to add?

**Comment by Joxit** [comment]
Hi, thank you for your feature request and using my project in your company :smile: 

So, you would like something like `env` but for labels in the history page ?

![image](https://user-images.githubusercontent.com/5153882/102808245-58f27a80-43c0-11eb-9cdb-3a54f67ac986.png)

Listing all labels is OK for you ? (without filters)

**Comment by CircleCode** [comment]
Hi @Joxit , thanks for the quick reply.
We still use docker registry UI in our company, but we won't need this feature (we changed the way we tag our images).
However, I think this would still be an appreciable feature.

**Comment by Joxit** [comment]
Hi there, I added this feature request to 2.2.0 milestone ! :rocket:
