### ISSUE TITLE
Want to add Certificates

### ISSUE THREAD

**Issue by karthiksonti24** [Joxit/docker-registry-ui#163]
Hi, 
I was looking for details how to add certificates for docker registry. I was not able to find any information. Can you please let me know as soon as possible.

**Comment by Joxit** [comment]
Hi,
Thank you for your issue and for using my project :smile: 

Please check old issues first. The issue #20 is about Docker registry and HTTPS/Certificates.
There is also an example [examples/issue-20](https://github.com/Joxit/docker-registry-ui/tree/master/examples/issue-20)

**Comment by karthiksonti24** [comment]
Joxit ,  

This issue is resolved after going through that sample example.thank you for your time.
