### ISSUE TITLE
Bottom entry gets run over by footer in UI

### ISSUE THREAD

**Issue by rodgermoore** [Joxit/docker-registry-ui#168]
Uhhh, need to say more? Images starting with a "z" are not visible in the UI.

![pastedImage](https://user-images.githubusercontent.com/12231719/106608048-3d07fa00-6564-11eb-9c44-4a3bc25a27eb.png)

**Comment by Joxit** [comment]
Hi, thank you for your issue, this was fixed with 476a96279e975564f61347895617c6511dfe6539 but I forgot the release :sweat_smile:

**Comment by Joxit** [comment]
Should be fixed now in v1.5.2 you can pull the image :smile:

**Comment by rodgermoore** [comment]
Muchos gracias senior :)
