### ISSUE TITLE
static-Tag is not the latest version (1.5.2)

### ISSUE THREAD

**Issue by Herr-Sepp** [Joxit/docker-registry-ui#169]
Thanks for the footer fix in 1.5.2

But if i pull the image with the static-tag
_docker pull joxit/docker-registry-ui:static_
I only got "Docker Registry UI v1.5.1"

Maybe there is somthing wrong with the new github-action 
(i see only _master-static_ and _${{steps.current-tag.outputs.tag}}-static_ as tag)

**Comment by Joxit** [comment]
Oops, sorry my fault :sweat_smile: should be fixed with [v1.5.3](https://github.com/Joxit/docker-registry-ui/releases/tag/1.5.3) and the new [run](https://github.com/Joxit/docker-registry-ui/actions/runs/552862046) :)
