### ISSUE TITLE
Problem with HTTPS

### ISSUE THREAD

**Issue by hacko2** [Joxit/docker-registry-ui#170]
I did all in the example [Issue 20](https://github.com/Joxit/docker-registry-ui/tree/master/examples/issue-20), but i don't understand "You will need to rewrite all the project configuration (replaces proxy_pass with our value)."
Only get:
ui_1 | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
ui_1 | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
ui_1 | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
ui_1 | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
ui_1 | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
ui_1 | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
ui_1 | sed: can't move '/etc/nginx/conf.d/default.confCaPkPD' to '/etc/nginx/conf.d/default.conf': Resource busy
ui_1 | sed: can't move '/etc/nginx/conf.d/default.confJogDGK' to '/etc/nginx/conf.d/default.conf': Resource busy
ui_1 | sed: can't move '/etc/nginx/conf.d/default.confepeBnm' to '/etc/nginx/conf.d/default.conf': Resource busy
docker-registry_ui_1 exited with code 1

**Comment by Joxit** [comment]
Hi,

Thank you for your issue, it seems that you are still using the environment variable `REGISTRY_URL` which is useless and cause this error when you are working with your own nginx configuration file. 

Sorry, the part you did not understood is a typo :sweat_smile: should be "your value".
```diff
-You will need to rewrite all the project configuration (replaces proxy_pass with our value).
+You will need to rewrite all the project configuration (replaces proxy_pass with your value).
```

If the name of your registry container is `docker-registry` and ins listening the port 5000 you will use 
```
      proxy_pass http://docker-registry:5000;
```

If you don't need the proxy pass, remove the location /2 block.

**Comment by hacko2** [comment]
Ok, thanks!!
