### ISSUE TITLE
Attach own Nginx.conf  into container

### ISSUE THREAD

**Issue by afteroot** [Joxit/docker-registry-ui#175]
Hi, I use this docker registry UI and I have an issue...

## Bug description
mount nginx.conf into container

## How to Reproduce

For UI bug, steps to reproduce the behavior:
1. Pull 'https://github.com/Joxit/docker-registry-ui/tree/main/examples/read-only-auth'
2. Run docker-compose up

```
ui_1        | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
ui_1        | /docker-entrypoint.sh: Launching /docker-entrypoint.d/90-docker-registry-ui.sh
ui_1        | sed: can't move '/etc/nginx/conf.d/default.confeacDcN' to '/etc/nginx/conf.d/default.conf': Resource busy
ui_1        | sed: can't move '/etc/nginx/conf.d/default.conffHNEML' to '/etc/nginx/conf.d/default.conf': Resource busy
ui_1        | sed: can't move '/etc/nginx/conf.d/default.confjoaKNh' to '/etc/nginx/conf.d/default.conf': Resource busy
```

**Comment by Joxit** [comment]
Hi, thank you for your issue.
This is caused by the environment variable `REGISTRY_URL`, you should remove it.

I will fix the example :slightly_smiling_face:

**Comment by afteroot** [comment]
ok, thanks for update
