### ISSUE TITLE
Management of local images

### ISSUE THREAD

**Issue by FStefanni** [Joxit/docker-registry-ui#179]
Hi,

**Is your feature request related to a problem? Please describe.**

I have to manage images both local to a server, and images stored in a private registry.
This project seems to support only the case of the private registry.

**Describe the solution you'd like**
Since this GUI works fine for the private registry, it could be nice to be able to use it to manage also images stored on the server.

**Describe alternatives you've considered**
The alternative is to do as I currently do: mange the server images by command line, with commands as `docker images`, `docker image delete`, etc..

**Additional context**

This probably requires to get access to the docker socket, and to use a different set of API, since it does not seem to have the same `registry` API.

Regards

**Comment by Joxit** [comment]
Hi, thank you for using my project and your feature requests.

Yes, this project is only for privates registries. API for registries and docker engines are not the same, I could not do a UI for both. This would make the project much too complex to maintain.

I suggest you to try this project for local image management : https://github.com/rakibtg/docker-web-gui

**Comment by FStefanni** [comment]
Hi,
thank you for the suggestion.
Regards.
