### ISSUE TITLE
msg="error authorizing context: basic authentication challenge for realm \"Registry Realm\": invalid authorization credential"

### ISSUE THREAD

**Issue by darthvaldr** [Joxit/docker-registry-ui#18]
hi, firstly thanks for creating this cool UI for docker private registries, i've been spending a bit of time this weekend trying to get it working and so far I've got it mostly working and can see/list my registry images. 

the issue i'm having here is the error message that keeps popping up when i'm browsing through my images:

`{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}`

now, I know this means my authentication is off somewhere, but I'm able to see & browse my repo images with no problem.

so I check my registry (running in a container) and see

`
time="2017-06-11T11:52:31Z" level=warning msg="error authorizing context: basic authentication challenge for realm \"Registry Realm\": invalid authorization credential" go.version=go1.7.3 http.request.host="dockeregistry.localhost:5000" http.request.id=61ec0a47-1a25-43ac-808e-2097731c660c http.request.method=GET http.request.referer="http://dockeregistry.localhost/" http.request.remoteaddr="172.16.45.11:55752" http.request.uri="/v2/_catalog" http.request.useragent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" instance.id=a86c3a58-c692-46ae-a6cd-7ed4659eee28 version=v2.6.1
172.16.45.11 - - [11/Jun/2017:11:52:31 +0000] "GET /v2/_catalog HTTP/2.0" 401 145 "http://dockeregistry.localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
time="2017-06-11T11:52:31Z" level=info msg="response completed" go.version=go1.7.3 http.request.host="dockeregistry.localhost:5000" http.request.id=2c66c4f6-722e-4f1b-b108-2e12ec2373c6 http.request.method=GET http.request.referer="http://dockeregistry.localhost/" http.request.remoteaddr="172.16.45.11:55758" http.request.uri="/v2/_catalog" http.request.useragent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" http.response.contenttype="application/json; charset=utf-8" http.response.duration=8.118256ms http.response.status=200 http.response.written=101 instance.id=a86c3a58-c692-46ae-a6cd-7ed4659eee28 version=v2.6.1
172.16.45.11 - - [11/Jun/2017:11:52:31 +0000] "GET /v2/_catalog HTTP/2.0" 200 101 "http://dockeregistry.localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
`

I can see one GET request which gets a 401, and then a following GET request which gets a 200 OK.. So I check my browser console and see the request which gets the 401 is missing the "authorization: Basic xxxxx" request header.

That's as far as I got troubleshooting wise - so, just wondering if you could have a look and possibly advise me where I might be going wrong?

some info that might put things in the right contexts:
- my registry is TLS-configured = certs and CA's all in the right place
- htpasswd setup with bcrypt switch (-Bbn) as per other issues I've seen in some forums
- docker login, pull, tag, push = all working as expected from the CLI

any help appreciated, thanks.

**Comment by Joxit** [comment]
Hi, thank you for your feedback.

This message should not be displayed each time.
This is due to the fact that it is impossible to know in advance if the registry is protected and if whe need to send an authentication request. 
The interface sends two requests, one without authentication, if it receives a status code 401, it starts again by sending the same request with an authentication request.

I will fix this issue as soon as possible.

**Comment by Joxit** [comment]
This should be fixed.
You can close the issue if all is good.

**Comment by darthvaldr** [comment]
working perfectly now. thank you! closing this issue.

**Comment by wildleek-ru** [comment]
docker logout hub-host
docker login  hub-host
