### ISSUE TITLE
Error « Operation not permitted » after upgrade to version 2.0

### ISSUE THREAD

**Issue by sadmin91** [Joxit/docker-registry-ui#186]
Hi, after an upgrade to version 2.0, I have an issue

## Bug description
When I start Docker container tag 2.0 on my Docker Swarm cluster (hosted on a Raspberry), I observe an error « Operation not permitted » on the log.

## How to Reproduce
My Docker service definition
```docker
docker service create \
--name registry-ui \
--network my-network \
--constraint node.role==manager \
-e NGINX_PROXY_PASS_URL=http://docker-registry:5000 \
-e DELETE_IMAGES=true \
-e SINGLE_REGISTRY=true \
--label traefik.enable=true \
--label "traefik.http.routers.registry-ui.rule=Host(\"registry-ui.my-domain.fr\")" \
--label traefik.http.routers.registry-ui.entrypoints=web \
--label traefik.http.services.registry-ui.loadbalancer.server.port=80 \
--health-cmd='curl --silent http://localhost >/dev/null' \
--health-start-period=10s \
--health-interval=5m \
joxit/docker-registry-ui:2.0
```

My Docker registry service definition
```docker
docker service create \
--name docker-registry \
--network my-network \
--constraint node.role==manager \
--mount "type=bind,source=/docker-registry/data,destination=/var/lib/registry,readonly=false" \
--publish published=5000,target=5000,mode=host \
--health-cmd='curl -L --silent http://localhost:5000/v2 >/dev/null' \
--health-start-period=10s \
--health-interval=5m \
vsellier/docker-registry-arm
```

## Expected behavior
Docker container start successfully

## System information

- OS: Debian 9.4 on Linux 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l
- Docker registry UI:
    - Version: 2.0
    - Server: Docker
    - Docker version: 18.09
    - Docker registry ui tag: 2.0
    - OS/Arch: linux/arm

## Additional context
This problem is not reproductible with 2.0-debian tag.
Before 2.0 migration, I used tag 1.5.4-static version.
Error log :
```
Error loading shared library libpcre.so.1: Operation not permitted (needed by /usr/sbin/nginx)
Error loading shared library libssl.so.1.1: Operation not permitted (needed by /usr/sbin/nginx)
Error loading shared library libcrypto.so.1.1: Operation not permitted (needed by /usr/sbin/nginx)
Error loading shared library libz.so.1: Operation not permitted (needed by /usr/sbin/nginx)
Error relocating /usr/sbin/nginx: TLS_method: symbol not found
Error relocating /usr/sbin/nginx: OCSP_response_get1_basic: symbol not found
Error relocating /usr/sbin/nginx: SSL_get_servername: symbol not found
Error relocating /usr/sbin/nginx: OPENSSL_sk_value: symbol not found
Error relocating /usr/sbin/nginx: EVP_DigestInit_ex: symbol not found
Error relocating /usr/sbin/nginx: X509_check_host: symbol not found
Error relocating /usr/sbin/nginx: X509_verify_cert: symbol not found
```

**Comment by Joxit** [comment]
Hi there, thank you for using my project :smile: 

Hum... That's odd... Can you replace the image `joxit/docker-registry-ui:2.0` by `nginx:alpine` ?
This issue seems to be related to nginx, maybe there is something wrong with their image :thinking: .

**Comment by sadmin91** [comment]
Hello,
I have the same behaviour with `nginx:alpine` image.

**Comment by Joxit** [comment]
Ok, that means it may be a nginx issue, it's not the first time something like this happens (see #95)
You can create an issue on https://github.com/nginxinc/docker-nginx/issues

**Comment by Joxit** [comment]
I close this issue, this should be fixed now
