### ISSUE TITLE
docker-registry-ui:2.0  causes blocked by CORS policy

### ISSUE THREAD

**Issue by tedsluis** [Joxit/docker-registry-ui#187]
Hi, I use this docker registry UI for quite some time and I have an issue moving from version 1.5 (joxit/docker-registry-ui:static) to 2.0 (/joxit/docker-registry-ui:2.0)

## Bug description

I tried to move over  from 1.5 (joxit/docker-registry-ui:static) to 2.0 (/joxit/docker-registry-ui:2.0), but I can not get it working. I get this error: An error occured: Check your connection and your registry must have `Access-Control-Allow-Origin` header set to `https://registry.bachstraat20.duckdns.org:5443`

## My setup

I have a single host with a registry:latest and docker-registry-ui. I use haproxy in front of docker-registry-ui, to expose it over https. Everything is running in containers.

I am not using docker compose. In stead I use podman, one pod with a registry container, a docker-registry-ui container and a haproxy container. I expect that podman is not effecting this issue. https://podman.io/whatis.html

```
/-------------\                     /---------\                   /--------------------\                      /----------\
| web browser | ---> port 5443 ---> | haproxy | ---> port 80 ---> | docker-registry-ui | ---> port 5000 ----> | registry |
\-------------/                     \---------/                   \--------------------/                      \----------/
```
## How to Reproduce

To move over from version 1.5 to 2.0 I changed my podman (same as docker) deployment. Below my new 2.0 deployment:
```bash
podman run  --name=registry-ui \
                  --pod=registrypod \
                  -e SINGLE_REGISTRY=true \
                  -e REGISTRY_URL="https://registry.bachstraat20.duckdns.org:5000" \
                  -e DELETE_IMAGES=true \
                  -e REGISTRY_TITLE="Bachstraat20"  \
                  joxit/docker-registry-ui:2.0
```
My 1.5 deployment is with the "static" TAG and without the environment variable *SINGLE_REGISTRY=true*.

Here my registry deployment:
```bash
podman run --name=registry \
    --pod=registrypod \
    -e REGISTRY_AUTH="htpasswd" \
    -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" \
    -e REGISTRY_AUTH_HTPASSWD_PATH="/auth/htpasswd" \
    -e REGISTRY_HTTP_TLS_CERTIFICATE="/certs/fullchain.pem" \
    -e REGISTRY_HTTP_TLS_KEY="/certs/privkey.pem" \
    -e REGISTRY_COMPATIBILITY_SCHEMA1_ENABLED=true \
    -e /var/lib/registry/certs:/certs:z \
    -e /var/lib/registry/data:/var/lib/registry:z \
    -e /var/lib/registry/auth:/auth:z \
    -e /var/lib/registry/config/config.yml:/etc/docker/registry/config.yml:z \
    registry:latest
```

## Expected behavior

I expected:

* a login dialog windows for my registry credentials after I started docker-registry-ui:2.0
* not to see the menu that show the dialogs to add, remove and change the endpoint of your docker registry, since I set SINGLE_REGISTRY=true

## What actually  happened 

When I refreshed my web browser, the 2.0 UI shows up and it reported: 
```
An error occured: Check your connection and your registry must have `Access-Control-Allow-Origin` header set to `https://registry.bachstraat20.duckdns.org:5443`
```
## Screenshots

Screenshot (chrome browser with inspect mode):
![Screenshot from 2021-05-05 07-15-59](https://user-images.githubusercontent.com/10097935/117101561-c652e680-ad76-11eb-8dd1-dae7d23897ca.png)

Console error in my chrome browser:
```bash
Access to XMLHttpRequest at 'https://registry.bachstraat20.duckdns.org:5000/v2/_catalog?n=100000' from origin 'https://registry.bachstraat20.duckdns.org:5443' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
docker-registry-ui.js:20 GET https://registry.bachstraat20.duckdns.org:5000/v2/_catalog?n=100000 net::ERR_FAILED
```

My docker-registry-ui container log reports:
```bash
10.88.0.18 - - [05/May/2021:05:44:51 +0000] "GET /?page=1 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "192.168.11.172"
10.88.0.18 - - [05/May/2021:05:44:51 +0000] "GET /favicon.ico HTTP/1.1" 200 303524 "https://registry.bachstraat20.duckdns.org:5443/?page=1" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "192.168.11.172"
```

My registry container log reports:
```bash
time="2021-05-05T05:41:12.217025051Z" level=warning msg="error authorizing context: basic authentication challenge for realm "Registry Realm": invalid authorization credential" go.version=go1.11.2 http.request.host="registry.bachstraat20.duckdns.org:5000" http.request.id=af22938a-667d-43a0-b9a1-c834598c22e7 http.request.method=GET http.request.referer="https://registry.bachstraat20.duckdns.org:5443/" http.request.remoteaddr="192.168.11.172:33530" http.request.uri="/v2/_catalog?n=100000" http.request.useragent="Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 
192.168.11.172 - - [05/May/2021:05:41:12 +0000] "GET /v2/_catalog?n=100000 HTTP/2.0" 401 145 "https://registry.bachstraat20.duckdns.org:5443/" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
```
This is understandable, since I didn't got the chance to enter my registry credentials in the docker-registry-ui.

My private docker registry configuration
```yml
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
## System information

- OS: Fedora 34
- Browser:
    - Name:  Chrome
    - Version: 90
- Docker registry UI:
    - Version: 2.0
    - Server: Fedora 34 (raspberry pi 4B 8GB)
    - Podman version: 3.1.2
    - Docker registry ui tag: 2.0
    - OS/Arch: amd64
    - Tools: podman

## Additional context

When I revert back to the 1.5 configuration, docker-registry-ui still works! I get the login window and I can login and browser through the registry. Here is my 1.5 deployment:
```bash
podman run  --name=registry-ui \
                  --pod=registrypod \
                  -e REGISTRY_URL="https://registry.bachstraat20.duckdns.org:5000" \
                  -e DELETE_IMAGES=true \
                  -e REGISTRY_TITLE="Bachstraat20"  \
                  joxit/docker-registry-ui:static
```

**Comment by Joxit** [comment]
Hi, thank you for using my project and your detailed issue with schema ! :smile: 

I think the issue is `REGISTRY_URL`. In the [migration guide](https://github.com/Joxit/docker-registry-ui/wiki/Migrating-from-1.x-to-2.x#new-and-renamed-options) the behavior of the option `REGISTRY_URL` moved to the option `NGINX_PROXY_PASS_URL` because this name is much clearer, thanks to this we know that the option will modify the nginx configuration.

Now you should use something like 

```
podman run  --name=registry-ui \
                  --pod=registrypod \
                  -e SINGLE_REGISTRY=true \
                  -e NGINX_PROXY_PASS_URL="https://registry.bachstraat20.duckdns.org:5000" \
                  -e DELETE_IMAGES=true \
                  -e REGISTRY_TITLE="Bachstraat20"  \
                  joxit/docker-registry-ui:2.0
```

**Comment by tedsluis** [comment]
Hi Joxit,

It works. That was easy!

I tried the NGINX_PROXY_PASS_URL environment variable before without luck, but my mistake was to use it in combination with the REGISTRY_URL. 

Thanks a lot!

**Comment by Joxit** [comment]
Yeah, you are welcome :smile: I hope you like new features from 2.0 :wink:
