### ISSUE TITLE
Delete does not work in Chrome

### ISSUE THREAD

**Issue by sepich** [Joxit/docker-registry-ui#19]
Delete button does not work in Chrome, showing message about enabling "Docker-Content-Digest" headers. This header exist in the response, but it is in lowercase. Putting breakpoint to warning message:
```
this.getAllResponseHeaders()
"docker-content-digest: sha256:9d080a16c6eee3bffa0552c2775c0a2d9b489d5e1e882c135e1898f5a9a33213
content-type: application/vnd.docker.distribution.manifest.v2+json
"
this.getAllResponseHeaders().includes("Docker-Content-Digest")
false
this.getAllResponseHeaders().includes("docker-content-digest")
true
```
Making the same request via curl I'm getting CamelCase headers.

**Comment by Joxit** [comment]
Hello, thank you for your feedback.

This should be now fixed.
You can close the issue if all is good.

**Comment by sepich** [comment]
Hmm, still don't work.
Pulled the image :static 57e79fb28a26.
I see code is changed now, but result is the same:
```
this.hasHeader("Docker-Content-Digest")
false
this.hasHeader("docker-content-digest")
true
```
In chrome Networking tab, all the header names are lowercased for /v2/name/manifests/ver query.
Do you need any other information?

**Comment by Joxit** [comment]
I'm really sorry... It's my fault, I misplaced the parenthesis of my regular expression...
I will fix this now!

**Comment by sepich** [comment]
No worries, it's me who don't know js well enough to make a PR with fix ;)
It works now, thank you!

**Comment by Joxit** [comment]
No problem :) feedback and issues are also very important.
Nice, that's cool. You're welcome :).

If you have any ideas to improve the user interface or other errors, feel free to create new issues ;).
