### ISSUE TITLE
Question: SHOW_CONTENT_DIGEST defaults to 'false'

### ISSUE THREAD

**Issue by BePo65** [Joxit/docker-registry-ui#194]
Hi, I use this great docker registry UI and I have an issue:

## Bug description

Today I updated my docker-registry-ui to V2.0.0.
I have a single repository, so until now I used the 'static' release and now switched to the 'latest' version..

The update was successful (after a small irritation, as  the meaning of the option `REGISTRY_URL` changed).

When I opened the registry-ui all my uploaded images were still available, but no `Content Digest` was shown.
Only when I added `SHOW_CONTENT_DIGEST=true` to my config, the  `Content Digest` reappeared.

Is it possible that the default value for this option changed to 'false' (by design or by chance)?

## How to Reproduce

My old configuration (will not show the content digest):
```sh
docker run -d -p 8000:80 --restart always --name=registry-ui \
  -e NGINX_PROXY_PASS_URL=https://docker-registry:5000 \
  -e PULL_URL=https://docker-registry:5000 \
  -e DELETE_IMAGES=true \
  -e SINGLE_REGISTRY=true \
  joxit/docker-registry-ui:arm32v7
```

My new configuration (that shows the content digest):
```
docker run -d -p 8000:80 --restart always --name=registry-ui \
  -e NGINX_PROXY_PASS_URL=https://docker-registry:5000 \
  -e PULL_URL=https://docker-registry:5000 \
  -e DELETE_IMAGES=true \
  -e SINGLE_REGISTRY=true \
  -e SHOW_CONTENT_DIGEST=true \
  joxit/docker-registry-ui:arm32v7
```

## Expected behavior

Documentation (default: true) and current behaviour (default: false) match.

## System information

    - Docker on Raspberry PI 3B
    - Docker version: 20.10.7
    - Docker registry ui tag: latest (2.0.0)
    - OS/Arch: Raspbian GNU/Linux 10 (buster)
    - Tools: portainer

**Comment by Joxit** [comment]
Hi, thank you for using my project :)

IIRC this has been fixed in [2.0.2](https://github.com/Joxit/docker-registry-ui/releases/tag/2.0.2) and #192. I've forgotten to regenerate dist folder :sweat_smile: a19c992d5a7ea97cbb9af05818bf1df1077bd3a3 should fix this.

Now I'm using GitHub actions to build multi arch images, so you can use `joxit/docker-registry-ui:latest` instead of `joxit/docker-registry-ui:arm32v7` (GH Actions generate dist folder before image build).

The tag `arm32v7` is built by Docker Hub and they will drop support for free automated build :disappointed:

**Comment by BePo65** [comment]
Thanks for the tip.
The above configuration using v2.0.0 was running fine:
the browser showed a list of my images and I could display the tags of an image and I could even delete a tag

Then I replaced `arm32v7` with `latest`.
As a result I got:

-  registry-ui v2.0.2 and the 
- browser showed me an empty list of my images and an 
- error in the browser console complaining about a tls time-out (the registry runs with https enabled).

Adding `REGISTRY_URL=https://docker-registry:5000` changed the behavior to:

- the browser showed me a list of my images (as expected).

When I tried to show the tags of an image I got a 

- list of the tags, but 
- without creation date and 
- without content digest (in spite of `SHOW_CONTENT_DIGEST=true`) and 
- tag deletion was grayed out.
- Additionally the console showed `Uncaught TypeError: crypto.subtle is undefined` in`docker-registry-ui.js:20:62744 with ` stack trace: `value http://docker-registry:8000/docker-registry-ui.js:20` ....

And here I am stuck. Any idea, what I have to change in my config to come back to the state I had with V2.0.0?

**Comment by Joxit** [comment]
Hum, can I have your browser and its version ?
Seems like [some browser can use this function only in HTTPS context](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle#browser_compatibility)... I will try to find a polyfill or something...

**Comment by Joxit** [comment]
Did you add the header `Docker-Content-Digest` to your docker registry server ?

See this part : https://github.com/Joxit/docker-registry-ui#registry-example

```yml
http:
  headers:
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
```

**Comment by melbcycle** [comment]
crypto.subtle issue here too. I created a multi-arch image of arm32, arm64 and amd64 to run on the swarm. So far it effects arm32 and arm64 (amd64 not tested but I don't think it's server side - or at least all architectures are effected).

It is effecting Firefox 89.0.2 (64-bit). However it works fine on MacOS with safari.

A priori it's a browser thing as you already suspect.

Great piece of software. Cheers.

**Comment by melbcycle** [comment]
Downloaded lastest cut from 2 days ago. Everything works now in all browsers on all platforms here. Cheers and thankyou.

**Comment by BePo65** [comment]
Reloading the image from the registry and restarting it solved the problem. Thanks for the help.
