### ISSUE TITLE
Alt-click does not work correctly with search

### ISSUE THREAD

**Issue by xdrew** [Joxit/docker-registry-ui#196]
Hi! Alt-click does not work correctly with search

## Bug description

My usecase is to find all tags by prefix, for ex dev- and delete them all. 
When I type dev- in Search in page field there are only dev tags shown on page
Then I alt-click on delete checkbox and all are checked
Then I delete dev- from search field and all tags on this page are checked

## Expected behavior

Dev- tags should only be checked

## System information

- OS: Windows 10
- Browser:
    - Name: Chrome
    - Version: 91.0.4472.101 
- Docker registry UI:
    - Version: 2.0
    - Server: docker
    - Docker registry ui tag: 2.0

**Comment by Joxit** [comment]
Hi, thank you for using my project and for your issue :+1: 

Bug confirmed, should be fixed in v2.0.3
