### ISSUE TITLE
Can't view platform specific tag info (wrong request url)

### ISSUE THREAD

**Issue by Mik4sa** [Joxit/docker-registry-ui#198]
## Bug description
Selecting a different platform tab/register on the history page of a tag to view it's information does nothing.

## How to Reproduce
Should be for every image/tag with multiple platforms the same. Just click on any other than the default and no new info should be displayed.

## Expected behavior
By selecting a different platform the info for this platform should appear.

## Screenshots
Having arm64 selected but still shows old info from first tab/register.
![image](https://user-images.githubusercontent.com/8343141/123137263-12a3d400-d454-11eb-8d54-1d25d6cff487.png)

## System information

- OS: Windows 10 x64
- Browser:
    - Name:  Edge
    - Version: 91.0.864.54
- Docker registry UI:
    - Version: 2.0.2
    - Server: docker
    - Docker version: latest
    - Docker registry ui tag: arm32v7
    - OS/Arch: arm32
    - Tools: docker-compose

## Additional context

I get these errors in browser console:
![image](https://user-images.githubusercontent.com/8343141/123137866-bdb48d80-d454-11eb-9637-ff7cc5295dae.png)

Just made a quick look with devtools, looks like `this.opts.registryUrl` is undefined here:
![image](https://user-images.githubusercontent.com/8343141/123138087-f3f20d00-d454-11eb-98fc-6ce9b1768d19.png)

**Comment by Joxit** [comment]
Hi, thank you for your issue and using my project :smile: 

Bug confirmed ! I will fix this ASAP

**Comment by Joxit** [comment]
Should be fixed in 2.0.4
