### ISSUE TITLE
Helm Chart improvement

### ISSUE THREAD

**Issue by criscola** [Joxit/docker-registry-ui#199]
Hello everyone, a couple of ideas for the Helm Chart in `examples/helm`:

- It would be nice to have the official Helm Chart uploaded to the ArtifactHub so that it could be pulled directly instead of requiring users to clone this repository. 
- It would be nice to specify [this Chart](https://artifacthub.io/packages/helm/twuni/docker-registry) as dependency in case the user wants to deploy docker-registry along docker-registry-ui. It would allow more powerful customization and leave the burden of maintenance on its owner. The Chart was updated 15 days ago so it looks well maintained.

I can take a shot and submit a pull-request for the latter and see what can be updated (e.g. it contains a deprecated version of docker-registry-ui which cannot be used currently) wdyt?

**Comment by Joxit** [comment]
Hello, thank you for using my project and for your issue :smile: 

I'm not familiar with Helm Chart, so I can accept any PR to improve and upgrade to v2.0 this example and then provide an official Helm Chart :smile:

**Comment by Joxit** [comment]
Hi there, welcome to the official Helm chart available here https://helm.joxit.dev/. The Chart is compatible with the latest docker registry UI :smile: (2.2.1)

Feel free to send me feedback if you try it. I will close this issue. I did not use twuni's Chart, but you can still set the twuni's Chart service address in docker-registry-ui [values.yaml](https://github.com/Joxit/helm-charts/blob/c32eb558dd0f9b125f47a00893fda887028b0e25/charts/docker-registry-ui/values.yaml#L17-L20) with `proxy: true`

I will close this issue :smile:
