### ISSUE TITLE
Labels and Env in history missing new line

### ISSUE THREAD

**Issue by Herr-Sepp** [Joxit/docker-registry-ui#200]
Thanks for docker registry UI!
## Bug description
Labels and enviroment variables are displayed as long string separated with comma
## How to Reproduce

For UI bug, steps to reproduce the behavior:
1. Click on history for any Image with enviroment variable or labels

## Expected behavior
In 1.9 each Label or ENV had a new line like a list which was much clearer

## Screenshots
![image](https://user-images.githubusercontent.com/10489458/123924191-ffc85c80-d989-11eb-8296-a79016a7674c.png)

## System information
- OS: Windows/Linux

- Browser: Chrome
- Docker registry UI:
    - Version: 2.0.4
    - Server: docker

    - Docker version: 20.10
    - Docker registry ui tag: latest
    - OS/Arch: linux/amd64

PS: on your Demo-Instance (https://joxit.dev/docker-registry-ui/demo/) the history does not work for any image.

**Comment by Joxit** [comment]
Hi, thank you for using my project and this issue.

Bug confirmed, I will fix this ASAP

**Comment by Joxit** [comment]
I know for the demo, I don't know how I can fix this... I'm using static files in the project (`https://raw.githubusercontent.com/Joxit/docker-registry-ui/master/demo`)... And history page causes CORS errors...

When I use the link `https://joxit.dev/docker-registry-ui/demo/` instead, the home is broken...
