### ISSUE TITLE
Typo in src/scripts/docker-image.js for sha256

### ISSUE THREAD

**Issue by PhracturedBlue** [Joxit/docker-registry-ui#201]
I was browsing the code, and I noticed this which is likely a typo:
File: src/scripts/docker-image.js
```
    this.on('get-sha256', function () {
      if (this.size !== undefined) {
        return this.trigger('sha256', this.sha256);
      }
      return this.fillInfo();
    });
```
I assume that `size` here should be `sha256`.  It is unlikely to cause an issue since I don't think sha256 can be det without a size, but I thought I'd mention it.

**Comment by Joxit** [comment]
Hi, thank you for using my project and taking time to review my code.

This should be fixed in 2.0.8 :smile:
