### ISSUE TITLE
Please update the dockerhub image to latest version

### ISSUE THREAD

**Issue by yurividal** [Joxit/docker-registry-ui#205]
Dockerhub image is on 2.0.2
Can you please update it to the latest?

**Comment by Joxit** [comment]
Hello, thant you for using my project :smile: 

I've downloaded the latest image and the version on docker hub is 2.0.8.

Did you run `docker pull joxit/docker-registry-ui:latest` ?

**Comment by Joxit** [comment]
I close this issue due to inactivity
