### ISSUE TITLE
Multiple static registries

### ISSUE THREAD

**Issue by glennpj** [Joxit/docker-registry-ui#211]
Is it possible to specify several static registry URLs and be able to switch between them in the interface?

**Comment by Joxit** [comment]
Hello, thank you for using my project.

No, this is not possible. You will need to add them manually in the UI when `SINGLE_REGISTRY` is false.

But it might be possible to initialise the local storage with a registry list :thinking:

**Comment by Joxit** [comment]
You should try the new options `DEFAULT_REGISTRIES` and `READ_ONLY_REGISTRIES` (not yet released but available in `main` or `master` tags)
