### ISSUE TITLE
Add a section in README.md for the system requirements

### ISSUE THREAD

**Issue by nickshanks347** [Joxit/docker-registry-ui#212]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**

Would just like an idea of the system requirements to run this, I'm sure other users will find this helpful. It would be useful if you could add a section in README.md for these details. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Joxit** [comment]
Hi, I close this issue due to inactivity.
