### ISSUE TITLE
Add hotkey to select search bar

### ISSUE THREAD

**Issue by Gjed** [Joxit/docker-registry-ui#213]
**Is your feature request related to a problem? Please describe.**
When there are many images if frustrating to scroll up and down the list of images. The search bar is really nice but when jumping from image to image I have to select it every time with the mouse.

**Describe the solution you'd like**
It would be nice to have a hotkey to select the search bar

**Describe alternatives you've considered**
Scroll down the list or use normal chrome ctrl+f

**Additional context**
I added a accesskey attribute in the dist docker-registry-ui.js as a workaround and it works nicely. I'm don't know enough of riot to put hands on the original source code.

Ps: consider to implement more keyboard navigation: it would be really nice!

**Comment by Joxit** [comment]
Hi there,
You can now select the search bar with the shortcut `CRTL` + `F` or `F3`. When the search bar is already focused, the shortcut will fallback to the default behavior.

For prometheus-style metrics, you should write an issue here [github.com/distribution/distribution](https://github.com/distribution/distribution), it's the project of the registry.
