### ISSUE TITLE
After migration columns not visible

### ISSUE THREAD

**Issue by HiranChaudhuri** [Joxit/docker-registry-ui#217]
Hi, I use this docker registry UI and I have an issue after following https://github.com/Joxit/docker-registry-ui/wiki/Migrating-from-1.x-to-2.x the image list looks like this:

![Screenshot from 2021-10-27 21-09-47](https://user-images.githubusercontent.com/6866487/139131785-06829c69-f5bd-419f-b38c-9b6842e88b63.png)

It strongly looks to me that the content digest is no longer displayed. Maybe more colums are missing compared to the previous display. I started the container like so:

docker run -d --name registry-ui --restart=unless-stopped --net registry -p 192.168.178.52:5001:80 -e SINGLE_REGISTRY=true -e "REGISTRY_TITLE=Homeserver A5" -e NGINX_PROXY_PASS_URL=https://registry:5000 -e "DELETE_IMAGES=true" -e REGISTRY_URL=http://homeserver.fritz.box:5001 joxit/docker-registry-ui:latest

## How to Reproduce

For UI bug, steps to reproduce the behavior:
1. From the homepage, expand some repository until the list of images is shown.
2. Check the colums that are displayed

## Expected behavior

I'd expect the columns to be displayed similar to the previous setup with the 1.x image. The documentation mentioned a variable "SHOW_CONTENT_DIGEST" which should default to 'true'. As I did not configure anything different I am wondering why the content digest is missing.

## System information

- OS: CentOS 7
- Browser:
    - Firefox 93.0 64bit on Ubuntu 20.04 LTS amd64
- Docker registry UI:
    - Version: 2.0.9
    - Server: docker image joxit/docker-registry-ui:latest (hash 0e6d7078a460)

    - Docker version: Docker version 20.10.10, build b485636
    - Docker registry ui tag: latest
    - OS/Arch: linux/amd64
    - Tools: none (triggered via Ansible)

**Comment by Joxit** [comment]
Hi, thank for using my project and for you for your issue :smile: 

I've updated the wiki and now I will do the README :+1:

**Comment by Joxit** [comment]
Fixed with f445570 (I've forgotten the auto-close action)
