### ISSUE TITLE
User access to specific registry

### ISSUE THREAD

**Issue by wiryonolau** [Joxit/docker-registry-ui#218]
Hi is it possible to allow only specific user to specific registry ( SINGLE_REGISTRY=false )

So UserA can only access RegsitryA not RegistryB

**Comment by Joxit** [comment]
Your use case is the same as #211 ?

**Comment by Joxit** [comment]
Oh, I understand now what you want, this is a access right issue. You need to configure your registries. For example RegistryB should not have UserA in its htpasswd file for example.

The UI cannot manage user rights.

**Comment by Joxit** [comment]
Hi, I close this issue due to inactivity.
