### ISSUE TITLE
Not working with index.html

### ISSUE THREAD

**Issue by FStefanni** [Joxit/docker-registry-ui#225]
Hi, I use this docker registry UI and I have an issue.
I am using the proxy scenario, to avoid cors/mixed content/authentication/etc issues.

## Bug description

If I access the ui as:
```
https://myserver.test/registry-ui/
```
it works fine.

If instead I access:
```
https://myserver.test/registry-ui/index.html
```
the GUI shows up, but complains as "Server not found", since it tries to access `https://myserver.test/registry-ui/index.html/v2/_catalog?n=100000` instead of `https://myserver.test/registry-ui/v2/_catalog?n=100000`.

## How to Reproduce

Probably using one of this project examples of the proxy scenario suffices.

## Expected behavior

To access the registry. Basically, the request should "strip" `index.html` from the url.

## System information

Using this project official docker image, v 2.0.1

**Comment by Joxit** [comment]
Hello, thank you for using my project :smile: 

Yes you're right, I should redirect every `index.html` to `/` (I do not like URLs ending with `index.html` :stuck_out_tongue:)
