### ISSUE TITLE
Deleting cross-platform images leaves the deleted image in an unknown state

### ISSUE THREAD

**Issue by agross** [Joxit/docker-registry-ui#226]
## Bug description

When the registry contains cross-platform images that are deleted via the UI, it leaves an undeletable image.

## How to Reproduce

For UI bug, steps to reproduce the behavior:
1. `docker login` to your registry
2. Create a builder: `docker buildx create --use`
2. Build a cross-platform busybox image:
   ```sh
   echo 'FROM busybox' | docker buildx build --platform linux/amd64,linux/arm64 \
                                             --tag your-registry.example.com/testing:1 \
                                             --push -
   ```
3. Open the registry UI and delete `testing:1`

UI config:
```
      SINGLE_REGISTRY: 'true'
      DELETE_IMAGES: 'true'
      NGINX_PROXY_PASS_URL: http://registry:5000
      REGISTRY_URL: https://your-registry.example.com
```

Registry config:
```
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
```

## Expected behavior

The deleted image should no longer be visible.

## Screenshots

<img width="672" alt="2022-01-15_10-00-11" src="https://user-images.githubusercontent.com/16245/149616152-47c189b0-c298-467d-9cd3-9dfc382a1da6.png">

## System information

- OS: docker
- Docker registry UI:
    - Version: 2.1.0
    - Server: docker

    - Docker version: Docker version 20.10.12, build e91ed57
    - Docker registry ui tag: latest
    - OS/Arch: linux/amd64
    - Tools: docker-compose

## Additional context

In the case of the screenshot above, the registry still contains the deleted image's tag:

```sh
$ docker container exec -it docker-registry_registry_1 ls /var/lib/registry/docker/registry/v2/repositories/gw/feedback/_manifests/tags
3.0.0-net-6.325  3.0.0-net-6.326
```

**Comment by Joxit** [comment]
Hi, thank you for using my project :smile: 

Issue confirmed, I should use the content digest from a request with `application/vnd.docker.distribution.manifest.list.v2+json` activated (same request as the history page)

**Comment by Joxit** [comment]
Hi there, this issue should be fixed with https://github.com/Joxit/docker-registry-ui/commit/7c0874694a8af2223951e7523f0a60b97ef78b5d
The fix will be first available on `main` tag. I will try to release the next version ASAP. Stay tuned :wink:
