### ISSUE TITLE
Don't show UI before auth

### ISSUE THREAD

**Issue by Yamakasi** [Joxit/docker-registry-ui#230]
**Is your feature request related to a problem? Please describe.**
When you use credentials the UI is still (empty) shown without being authenticated

**Describe the solution you'd like**
Blank page before auth

**Describe alternatives you've considered**
(Another) Nginx reverse proxy in front of it all

**Comment by Joxit** [comment]
Hi, thank you for using my project :smile: 

There is already an empty page when someone tries to connect to it without having the rights.
But I can create a page with a big 401 / 403 / 404 :thinking:
