### ISSUE TITLE
Support for dark mode

### ISSUE THREAD

**Issue by xZero707** [Joxit/docker-registry-ui#235]
First of all, this is an amazing project. Simple to use yet powerful. Thank you. :beer: 

**Is your feature request related to a problem? Please describe.**
As a developer myself, I often spend my time in the terminal, IDE, etc where everything is dark (by choice).  
Then when I end up in this UI, it's just dazzling, especially during the small hours.  

**Describe the solution you'd like**
It would be nice to have either a toggle or ENV variable to switch UI to dark.  
The possibility to override the default style would also work for many.

**Describe alternatives you've considered**
Using client-side plugins like Tampermonkey.
So far [this extension](https://addons.opera.com/en/extensions/details/dark-mode/) works great, but it's a struggle since it affects all websites, so it needs to be toggled on and off. 

**Additional context**
-

**Comment by Joxit** [comment]
Hi there,

Thank you for your Feature Requests :smile: 
This was on my task list, but I don't have much time :disappointed:

**Comment by Joxit** [comment]
Hi there, happy new year and good news for all of you, dark mode is coming !
Please checkout #283, you can give me feedback if you want :smile:
