### ISSUE TITLE
Being able to remove (empty) repositories with button

### ISSUE THREAD

**Issue by Yamakasi** [Joxit/docker-registry-ui#236]
**Is your feature request related to a problem? Please describe.**
I would like to be able to remove an (empty) repository like I can remove an image... I guess the garbage collector would do the rest ?

**Describe the solution you'd like**
Have a delete button to remove an empty repository

**Describe alternatives you've considered**
All kinds of scripts to remove empty repositories but I'm not able find any, they still exit (in this UI)

**Additional context**
I know this has been discussed a lot and it's not directly a docker-registry-ui issue but as there is a button to "delete" images it would be great to have the same for repositories... unless someone knows a way how to remove empty repo's with a script.

**Comment by Duvel** [comment]
+1

**Comment by mr-dxdy** [comment]
+1

**Comment by Joxit** [comment]
Hi there and thank you for using my project.

This is related to the docker registry server, I cannot remove empty images from the ui :confused: see #77

**Comment by mrmillers** [comment]
A very ad-hoc way to automate garbage collection by customizing registry image if you are still interested:

Dockerfile:
```
FROM registry:2

RUN apk --no-cache add findutils && \
    rm -rf /var/cache/apk/*

COPY entrypoint.sh /entrypoint.sh
COPY cleanup.sh /cleanup.sh
RUN chmod +x /*.sh
ENTRYPOINT [ "/entrypoint.sh" ]
```

entrypoint.sh:
```
#!/bin/sh

# cleanup: remember to enable init for docker run and docker-compose
(
    while true; do
        sleep 600
        /cleanup.sh
    done
) &

exec registry serve /etc/docker/registry/config.yml
```

cleanup.sh:
```
#!/bin/sh

registry garbage-collect /etc/docker/registry/config.yml -m
find /var/lib/registry -empty -type d -delete
for d in /var/lib/registry/docker/registry/v2/repositories/*; do
    echo "Processing $d"
    if [ ! -d $d/_manifests ]; then
        echo "Will delete $d"
        rm -rf $d
    fi
done
```

**Comment by radziejewicz** [comment]
> #!/bin/sh
> 
> registry garbage-collect /etc/docker/registry/config.yml -m
> find /var/lib/registry -empty -type d -delete
> for d in /var/lib/registry/docker/registry/v2/repositories/*; do
>     echo "Processing $d"
>     if [ ! -d $d/_manifests ]; then
>         echo "Will delete $d"
>         rm -rf $d
>     fi
> done

Thanks @mrmillers

**Comment by jpbaril** [comment]
@mrmillers (or @radziejewicz) Sorry for the newbie question, but why create a custom image and not simply override the container entrypoint and command ?

I did the following in my docker-compose.yml and it seems to work:

```
...
volumes:
  - data:/var/lib/registry
  - ${PWD}/config.yml:/etc/docker/registry/config.yml
  - ${PWD}/entrypoint.sh:/entrypoint.sh
  - ${PWD}/cleanup.sh:/cleanup.sh
entrypoint: ['/entrypoint.sh']
command: []
```

**Comment by mrmillers** [comment]
Your solution also works if you start your registry locally. But the local mount won't work when managing a remote docker target. (Eg, a ssh docker context).
