### ISSUE TITLE
Wrong url, to get tags list in subgroups

### ISSUE THREAD

**Issue by wntbrian** [Joxit/docker-registry-ui#24]
![image](https://user-images.githubusercontent.com/31837915/32584121-9fae500c-c542-11e7-9847-3012267e2507.png)

Generate url:
http://ui-docker.kube.local/#!/taglist/kube/docker, with referrer to 
https://docker.local/v2/kube/docker/tags/list
but it's wrong,
needed be:
https://docker.local/v2/kube/docker/bower/tags/list

**Comment by Joxit** [comment]
Thank you for your feedback.

This should be fixed now :-)

**Comment by Joxit** [comment]
You can close the issue if all is good :smile:

**Comment by wntbrian** [comment]
it's Ok. Thank.
