### ISSUE TITLE
main tag of docker image lacks css file

### ISSUE THREAD

**Issue by tkarls** [Joxit/docker-registry-ui#242]
## Bug description

The main tag of the docker image lacks the css file in /usr/share/nginx/html/
## How to Reproduce

Use the main tag and the browser cannot find the docker-registry-ui.css file (404 not found).

## Expected behavior

The css file should be found

## Screenshots

This is what the /usr/share/nginx/html/ directory in the container looks like
![image](https://user-images.githubusercontent.com/5672845/160408632-4c2eead3-afc7-4acd-a1ef-dfd65fc02d17.png)

The image hash used is: sha256:6c95840e1ae5624fb934ab26bc3bd3b6a549ffb07f805a443edf7476b1527a89

I hope I did not miss something obvious, but the latest tag include the css file and there the GUI renders properly.

**Comment by TacoNaco47** [comment]
Same problem here: 

![image](https://user-images.githubusercontent.com/42797589/161062234-b8610afd-9e09-48c4-94df-98dd21a28854.png)

Running the docker-registry-ui on a Kubernetes (kubeadm, v1.22.5) environment.

**Comment by Joxit** [comment]
Hi there, thank you for using my project and your issue.

Confirmed, the CI build had an error without failing the job https://github.com/Joxit/docker-registry-ui/runs/5703710915?check_suite_focus=true
![image](https://user-images.githubusercontent.com/5153882/161305481-4a989596-a4ff-41f2-a9b5-0d24e26d8d73.png)

**Comment by Joxit** [comment]
Now the CI will fail when a file is missing. Now this should be fixed, pull the latest image :smile:

**Comment by TacoNaco47** [comment]
> Now the CI will fail when a file is missing. Now this should be fixed, pull the latest image 😄

Great Work! Thank you @Joxit😁
