### ISSUE TITLE
Delete button has no effect

### ISSUE THREAD

**Issue by BlueskyFR** [Joxit/docker-registry-ui#248]
Hi, thanks for the cool project!

On my side, when I click the confirm button to delete an image, nothing happens. The DELETE request is not even made.
As per reading this file's code: `src/components/tag-list/tag-table.riot`, I notice that no code is actually deleting the image, the `toDelete` set is only emptied.

Is this only me or is there really a problem here?

Thanks in advance!

**Comment by BlueskyFR** [comment]
Ok so the problem comes from the documentation:

The following line **MUST** actually be included in the config even if the registry does not require any credentials:
```yml
 Access-Control-Allow-Headers: ['Authorization', 'Accept']
```

**Comment by BlueskyFR** [comment]
See #249

**Comment by Joxit** [comment]
Hi, thank you for using my project :smile: 

Nice catch, but IMO the required header to fix your issue may be only `Accept` without `Authorization` ?
