### ISSUE TITLE
Run Without Docker

### ISSUE THREAD

**Issue by makeitstatic** [Joxit/docker-registry-ui#252]
I have an environment where I cannot use docker. I would like to run this on a VM which is hosting my private registry.

Would it be possible to provide any support on how to configure a run of this application without using the Dockerfile?
I am no JS pro so picking the project apart may take me an excruciating amount of time.

I did try the Electron approach but I get so many errors like:
An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/root/electron/node_modules/keytar'.
Error: `gyp` failed with exit code: 1

The above error still occurs even after rm package-lock.json and running the npm commands again.

I have gathered the environment variables that need to be set and that NGINX is used to serve it but that is about as far as I get.

Any help would be greatly appreciated!

**Comment by Joxit** [comment]
Hi, sorry for the late delay. Thank you for using my project :)

Did you try the hosted demo? It's easy you just need to use this url and add your registry server url: `https://joxit.dev/docker-registry-ui/demo/?url=your-registry-server-url>`

**Comment by Joxit** [comment]
Hi there, I closing the issue due to inactivity
