### ISSUE TITLE
http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by BatUnt** [Joxit/docker-registry-ui#256]
Hi, I use this docker registry UI and I have an issue...

## Bug description
The push refers to repository [10.43.240.20:5000/v2/pkt]
Get "https://10.43.240.20:5000/v2/": http: server gave HTTP response to HTTPS client

I'm using your k8s settings
any advice on how to change http to https or vice versa?

**Comment by faust64** [comment]
Hi,

Either you can configure your webserver enabling HTTPS, setting it up with your own certificates. Then: you would need your container runtime to trust the CA signing those certificates (or ignore tls verification).
Or: you can leave your registry setup as it is, and configure your container runtime pulling images using http.

Note: you don't need your container runtime pulling from docker-registry-ui. It would act as a proxy, but you could very well pull images directly out of your registry. Which may already serve clients using HTTPS. Using certificates that might already be trusted by your runtime ...

Anyway: you would have to configure your container runtime integrating with your registry.
For sure, this error isn't a bug: it's some missing configuration

**Comment by BatUnt** [comment]
I understand that, thank you for your help
