### ISSUE TITLE
all tags selection to delete

### ISSUE THREAD

**Issue by FrancYescO** [Joxit/docker-registry-ui#258]
**Is your feature request related to a problem? Please describe.**
mainly not, just an easy way to delete all images except latest/a specific one

**Describe the solution you'd like**
preselect first item, select the last one while pressing SHIFT all in the middle will be automatically selected

**Describe alternatives you've considered**
the second click of the checkbox in the table header will select all items

**Comment by Joxit** [comment]
Hi, thank you for using my project :smile: 

Checkout the [feature list](https://github.com/Joxit/docker-registry-ui#features), I think what you want is this one:
* Select all tags with ALT + Click to delete (see https://github.com/Joxit/docker-registry-ui/issues/80).

**Comment by FrancYescO** [comment]
mainly yes, a pretty hidden feature :D

idk if you wold consider the use of the shift key that is a more standard way to interact with a multiselect :P

**Comment by Joxit** [comment]
If fact, there is also a tooltip for this shortcut :sweat_smile: 
![image](https://user-images.githubusercontent.com/5153882/181996639-01bcf78e-b8d0-4f5b-b2a1-33e072356a5a.png)

Anyway, the shift + Click may be interesting too :smile:
