### ISSUE TITLE
Basic authentication 

### ISSUE THREAD

**Issue by 605adi** [Joxit/docker-registry-ui#262]
I want my private registry to use username and password when using from browser.
So i have followed exactly the same Steps defined in **examples directory :-**

https://github.com/Joxit/docker-registry-ui/tree/main/examples/proxy-headers

I could able to get the signin page but not able to login

what is the Username and password.
Thanks

**Comment by faust64** [comment]
You created /etc/nginx.env with `NGINX_PROXY_HEADER_Authorization=Basic cmVnaXN0cnk6dWk=`?
Then according to the example your username is registry, and password is ui

**Comment by Joxit** [comment]
That's right, the username is `registry` and the password is `ui` as written in the README

**Comment by Joxit** [comment]
Hi, I close this issue due to inactivity.
