### ISSUE TITLE
Cannot see creation date, size and when clicked on the history icon it displays a spinner but shows nothing

### ISSUE THREAD

**Issue by hicnar** [Joxit/docker-registry-ui#263]
I have a repository with one artefact in it, following is the docker-compose script that starts up my setup

```yaml
version: '3.6'
services:
  DockerUtilsRegistry:
    image: registry:2.8.1
    container_name: docker-utils-registry
    volumes:
      - /volume1/docker/utils-registry:/var/lib/registry
    ports:
      - '5050:5000'
    environment:
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: "['*']"
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'


  DockerRegistryUi:
    image: joxit/docker-registry-ui:latest
    container_name: docker-registry-ui
    depends_on:
      - DockerUtilsRegistry
    ports:
      - '8082:80'
    environment:
      - REGISTRY_TITLE=ProactiveApps
      - REGISTRY_URL=http://192.168.1.6:5050
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
```

And here is what I can see when I open the ui in the browser 

![Screenshot 2022-08-31 at 23 13 41](https://user-images.githubusercontent.com/1816194/187795113-e2e37b5d-27f3-4f9a-85bc-fd4f2a247ff4.png)

When I click the history icon here's what gets displayed

      
![Screenshot 2022-08-31 at 23 18 55](https://user-images.githubusercontent.com/1816194/187795275-5f2402bf-5fbc-4ad4-ade7-42e44a632c07.png)

**Comment by Joxit** [comment]
Hi, thank you for using my project and submitting issues :smile: 

Can I have the content of your console and failing requests from network ?  (`F12`)

**Comment by hicnar** [comment]
Below is what I executed to start up the containers in a non daemon mode so that you can see the logs and everything below this line "2022/09/14 18:32:35 [notice] 1#1: start worker process 51" is what got printed once I opened the ui
Hope this is what you asked for (not sure about the failing requests from the network bit) and do not hesitate to ask for more stuff if needed. 

docker-compose -f docker-compose-registry.yml up
[+] Running 3/3
 ⠿ Network docker-compose_default   Created                                                                                                                                                                                                                                         0.3s
 ⠿ Container docker-utils-registry  Created                                                                                                                                                                                                                                         0.1s
 ⠿ Container docker-registry-ui     Created                                                                                                                                                                                                                                         0.1s
Attaching to docker-registry-ui, docker-utils-registry
docker-utils-registry  | time="2022-09-14T18:32:34.564122706Z" level=info msg="Starting upload purge in 43m0s" go.version=go1.16.15 instance.id=6134934e-4f38-42ee-88fe-ea7665be8e82 service=registry version="v2.8.1+unknown" 
docker-utils-registry  | time="2022-09-14T18:32:34.564230256Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.16.15 instance.id=6134934e-4f38-42ee-88fe-ea7665be8e82 service=registry version="v2.8.1+unknown" 
docker-utils-registry  | time="2022-09-14T18:32:34.564273135Z" level=info msg="redis not configured" go.version=go1.16.15 instance.id=6134934e-4f38-42ee-88fe-ea7665be8e82 service=registry version="v2.8.1+unknown" 
docker-utils-registry  | time="2022-09-14T18:32:34.577882853Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.16.15 instance.id=6134934e-4f38-42ee-88fe-ea7665be8e82 service=registry version="v2.8.1+unknown" 
docker-utils-registry  | time="2022-09-14T18:32:34.578119862Z" level=info msg="listening on [::]:5000" go.version=go1.16.15 instance.id=6134934e-4f38-42ee-88fe-ea7665be8e82 service=registry version="v2.8.1+unknown" 
docker-registry-ui     | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
docker-registry-ui     | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
docker-registry-ui     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
docker-registry-ui     | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
docker-registry-ui     | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
docker-registry-ui     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
docker-registry-ui     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
docker-registry-ui     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/90-docker-registry-ui.sh
docker-registry-ui     | /docker-entrypoint.sh: Configuration complete; ready for start up
docker-registry-ui     | 2022/09/14 18:32:35 [notice] 1#1: using the "epoll" event method
docker-registry-ui     | 2022/09/14 18:32:35 [notice] 1#1: nginx/1.21.6
docker-registry-ui     | 2022/09/14 18:32:35 [notice] 1#1: built by gcc 10.3.1 20211027 (Alpine 10.3.1_git20211027) 
docker-registry-ui     | 2022/09/14 18:32:35 [notice] 1#1: OS: Linux 4.4.180+
docker-registry-ui     | 2022/09/14 18:32:35 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
docker-registry-ui     | 2022/09/14 18:32:35 [notice] 1#1: start worker processes
docker-registry-ui     | 2022/09/14 18:32:35 [notice] 1#1: start worker process 44
docker-registry-ui     | 2022/09/14 18:32:35 [notice] 1#1: start worker process 45
docker-registry-ui     | 2022/09/14 18:32:35 [notice] 1#1: start worker process 46
docker-registry-ui     | 2022/09/14 18:32:35 [notice] 1#1: start worker process 47
docker-registry-ui     | 2022/09/14 18:32:35 [notice] 1#1: start worker process 48
docker-registry-ui     | 2022/09/14 18:32:35 [notice] 1#1: start worker process 49
docker-registry-ui     | 2022/09/14 18:32:35 [notice] 1#1: start worker process 50
docker-registry-ui     | 2022/09/14 18:32:35 [notice] 1#1: start worker process 51
docker-registry-ui     | 192.168.96.1 - - [14/Sep/2022:18:34:13 +0000] "GET / HTTP/1.1" 200 1592 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15" "-"
docker-registry-ui     | 192.168.96.1 - - [14/Sep/2022:18:34:13 +0000] "GET /docker-registry-ui.css HTTP/1.1" 200 33597 "http://192.168.1.6:8082/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15" "-"
docker-registry-ui     | 192.168.96.1 - - [14/Sep/2022:18:34:13 +0000] "GET /docker-registry-ui.js HTTP/1.1" 200 131587 "http://192.168.1.6:8082/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15" "-"
docker-registry-ui     | 192.168.96.1 - - [14/Sep/2022:18:34:13 +0000] "GET /fonts/Roboto-Regular.woff2 HTTP/1.1" 200 5468 "http://192.168.1.6:8082/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15" "-"
docker-registry-ui     | 192.168.96.1 - - [14/Sep/2022:18:34:13 +0000] "GET /fonts/Roboto-Light.woff2 HTTP/1.1" 200 15784 "http://192.168.1.6:8082/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15" "-"
docker-utils-registry  | time="2022-09-14T18:34:13.275164431Z" level=info msg="response completed" go.version=go1.16.15 http.request.host="192.168.1.6:5050" http.request.id=c2de8348-1350-4181-b9ca-82cbc3f7a1ca http.request.method=GET http.request.referer="http://192.168.1.6:8082/" http.request.remoteaddr="192.168.96.1:33058" http.request.uri="/v2/_catalog?n=100000" http.request.useragent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15" http.response.contenttype="application/json; charset=utf-8" http.response.duration=3.107599ms http.response.status=200 http.response.written=27 
docker-utils-registry  | 192.168.96.1 - - [14/Sep/2022:18:34:13 +0000] "GET /v2/_catalog?n=100000 HTTP/1.1" 200 27 "http://192.168.1.6:8082/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"
docker-registry-ui     | 192.168.96.1 - - [14/Sep/2022:18:34:13 +0000] "GET /fonts/MaterialIcons-Regular.woff2 HTTP/1.1" 200 55208 "http://192.168.1.6:8082/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15" "-"
docker-registry-ui     | 192.168.96.1 - - [14/Sep/2022:18:34:13 +0000] "GET /favicon.ico HTTP/1.1" 200 303524 "http://192.168.1.6:8082/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15" "-"
docker-utils-registry  | time="2022-09-14T18:34:18.058218012Z" level=info msg="response completed" go.version=go1.16.15 http.request.host="192.168.1.6:5050" http.request.id=884a43f9-e4a8-446a-9975-acf5e500d4f0 http.request.method=GET http.request.referer="http://192.168.1.6:8082/" http.request.remoteaddr="192.168.96.1:33058" http.request.uri="/v2/maven/tags/list" http.request.useragent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15" http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.036796ms http.response.status=200 http.response.written=45 
docker-utils-registry  | 192.168.96.1 - - [14/Sep/2022:18:34:18 +0000] "GET /v2/maven/tags/list HTTP/1.1" 200 45 "http://192.168.1.6:8082/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"
docker-utils-registry  | 192.168.96.1 - - [14/Sep/2022:18:34:18 +0000] "OPTIONS /v2/maven/manifests/3.8.3-openjdk-17 HTTP/1.1" 200 0 "http://192.168.1.6:8082/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"
docker-utils-registry  | time="2022-09-14T18:34:18.069028749Z" level=info msg="response completed" go.version=go1.16.15 http.request.host="192.168.1.6:5050" http.request.id=87e495cf-cf84-4771-bc09-5dfc2c05dc0a http.request.method=OPTIONS http.request.referer="http://192.168.1.6:8082/" http.request.remoteaddr="192.168.96.1:33058" http.request.uri="/v2/maven/manifests/3.8.3-openjdk-17" http.request.useragent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15" http.response.duration=1.828008ms http.response.status=200 http.response.written=0 
docker-registry-ui     | 192.168.96.1 - - [14/Sep/2022:18:34:18 +0000] "GET /fonts/Roboto-Bold.woff2 HTTP/1.1" 200 14952 "http://192.168.1.6:8082/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15" "-"

**Comment by Joxit** [comment]
Oh, I'm sorry, I was talking about your browser console, it seems that you are on firefox, this is what I need : https://firefox-source-docs.mozilla.org/devtools-user/browser_console/index.html

**Comment by clyvari** [comment]
I had the same problem, turns out I was missing CORS Headers. Check the exemple in the README:

```
http:
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['http://127.0.0.1:8000']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
```

**Comment by welldo2017** [comment]
> I had the same problem, turns out I was missing CORS Headers. Check the exemple in the README:
> 
> ```yaml
> http:
>   headers:
>     X-Content-Type-Options: [nosniff]
>     Access-Control-Allow-Origin: ['http://127.0.0.1:8000']
>     Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
>     Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
>     Access-Control-Max-Age: [1728000]
>     Access-Control-Allow-Credentials: [true]
>     Access-Control-Expose-Headers: ['Docker-Content-Digest']
> ```

thanks so much, it fix my same bug

**Comment by Joxit** [comment]
So I can close the issue ?

**Comment by hicnar** [comment]
@Joxit it is the CORS related config that I am missing in my setup.
Would appreciate if you could point me to the part of the docs that I need to apply in order to fix it.

**Comment by Joxit** [comment]
You can try this example : https://github.com/Joxit/docker-registry-ui/tree/main/examples/ui-as-standalone

Use the `simple.yml` docker-compose and use a file for your registry configuration instead of environment variables.

**Comment by Joxit** [comment]
Hi, I close this issue due to inactivity.
