### ISSUE TITLE
Upgrading proxy_pass HTTP version from 1.0 to 1.1

### ISSUE THREAD

**Issue by clyvari** [Joxit/docker-registry-ui#270]
Hello,

I was having some issue communicating with my registry (which is already hosted "somewhere else" than Joxit).

By default nginx `proxy_pass` requests are made using HTTP 1.0, and it turns out the reverse proxy in front of my registry does not accept HTTP 1.0 requests and respond with `426 Upgrade Required`

It is fixed by setting `proxy_http_version 1.1;` inside the `default` nginx conf.

I successfully tested this by opening a shell inside the container and manually settings this option.

#### My question is:
Would you be open to add this option in the config ? I cannot imagine a case where it would cause an issue since docker-registry does support HTTP 1.1
Or would maybe having a flag to enable / disable the http version ? But again, I cannot see a case where someone would want to change this back to HTTP 1.0

I do not know the reason why nginx default to this value, although I suspect it is for backward compatibility issues

**Comment by clyvari** [comment]
If you are OK with simply setting the option, I could send a PR with this: https://github.com/clyvari/docker-registry-ui/commit/9b319035790869d6dfceb62182e981825033745b

**Comment by Joxit** [comment]
Hi, thank you for using my project and submitting feature requests :smile: 

Since the docker registry server is supporting http 1.1... This is a safe change !

**Comment by Joxit** [comment]
Will be published in 2.3.1 and I added your name in [contributor list](https://github.com/Joxit/docker-registry-ui/blob/main/CONTRIBUTORS.md) :smile:
