### ISSUE TITLE
Improve visibility of multi-architecture images

### ISSUE THREAD

**Issue by lippl** [Joxit/docker-registry-ui#271]
**Is your feature request related to a problem? Please describe.**
I am missing some visibility to see what architecture my images are available for, or in case it's multiple to see this without checking the history page for each of them individually. The manifest is already fetched and the info available in the tag list view, so why not visualize it :)

**Describe the solution you'd like**
I would love an additional column in the tag list which displays the os/architecture/variant. If it has only one, just display it and in case it has multiple, just write multiple and optionally display them on hovering. A click could just open the history page again. The column could also be hidden when small devices are used.

**Describe alternatives you've considered**
Otherwise the History column/button could be improved to intuitevly let the user know, that he can find infos about multi-architecture. After all the label history is a bit misleading or at least not advertising the full potential of what a user can expect to find when clicking it, as it does rather show all kinds of further details of an image besides the history.

**Additional context**
-

**Comment by Joxit** [comment]
Hi, thank you for using my project and submitting feature requests :smile: 

I'm afraid it will add too much information to the page... Knowing that the Content Digest already takes up a lot of space... :confused: 

I like the alternative, plus I also have this feature request https://github.com/Joxit/docker-registry-ui/issues/261 to add in the history page (or a new one :shrug:)

**Comment by Joxit** [comment]
Hi there, I've finally worked on this feature requests and here is the result:
![image](https://github.com/Joxit/docker-registry-ui/assets/5153882/ec49c5fd-f29e-4c0b-ba08-2c78f5d7b7d1)

It will be available in [2.5.0](https://github.com/Joxit/docker-registry-ui/milestone/6)
