### ISSUE TITLE
Docker image save + download

### ISSUE THREAD

**Issue by Wetwer** [Joxit/docker-registry-ui#273]
**Describe the solution you'd like**
The possibility to download create a .tar/.tar.gz artifact. This would be quite useful.
Add a download image button for each tag in the repository.
This would trigger `docker image save some-image:1.1.1 -o some-image:1.1.1.tar.gz`

![image](https://user-images.githubusercontent.com/25004579/194850709-f30be8a9-c2a5-40e4-bab0-972f8453b982.png)

**Comment by Joxit** [comment]
Hi, thank you for using my project :smile: 

> This would trigger `docker image save some-image:1.1.1 -o some-image:1.1.1.tar.gz`

This means it will copy the command line ?

**Comment by Wetwer** [comment]
ah ok just had a look at the code, so all the data is gathered by using the docker registry Rest API? The Registry API doesnt support image downloads to files as far as i see.
I was thinking of a custom API Endpoint -> `/image/{imageName:tag}/download` that would trigger the command.
But if there is no custom API this wont be possible...

**Comment by Joxit** [comment]
Yes you can only download blobs (one layer) of the image via the API
