### ISSUE TITLE
Pagination doesn't work properly when viewing tags for an image.

### ISSUE THREAD

**Issue by dgiles-github** [Joxit/docker-registry-ui#274]
Hi, I use this docker registry UI and I have an issue...

## Bug description

We have an image that has about approximately 3000 tags and clicking on the individual page numbers and or clicking the next page doesn't always take you to the right page. Manually changing the page in the URL does seem to work.

Clicking on the Go to beginning and Go to end buttons seem to work, the problem specifically is switching between pages or clicking on a page number.

Using version docker-registry-ui v2.3.0

Name of the tag is joxit/docker-registry-ui:2.3.0

## How to Reproduce

For UI bug, steps to reproduce the behavior:
1. Go to the main page and click a container that has a large amount of tags
2. Switch between pages using the arrow buttons 5 or 6 times and it stops switching.

## Expected behavior

- Individual page buttons should always take you to the correct page.
- Forward and back buttons should take you one page forward and one page back respectively.

## System information

Browser :
  Name : Chrome 
  Version : 106.0.5249.103

OS: Mac
Version: 12.9 [Monterey]

Docker registry UI:
    - Version: 2.3.0
    - Server: docker
    
- Docker version: 18.09.3
- Docker registry ui tag: 2.3.0
- OS/Arch: linux
- Tools: mesos

**Comment by Joxit** [comment]
Hi thank you for using my project and submitting issues :smile: 

Bug confirmed !

**Comment by Joxit** [comment]
Should be fixed in 2.3.2
