### ISSUE TITLE
Show size with a digit after the comma for image sizes between 1 and 10 GB

### ISSUE THREAD

**Issue by MartinHerren** [Joxit/docker-registry-ui#276]
**Is your feature request related to a problem? Please describe.**
Starting with a size of 1000 MB, the compressed image size shown in the `Size` column, is given in GB and rounded to the higher GB.
So an image with a size of 950 MB shows as 950 MB, one with 1050 MB will show as 2 GB, which can be confusing about why there was such a jump in image size when in reality there was only a small increase.

**Describe the solution you'd like**
For images >=1GB and <10 GB, show the size with 2 significant digits, that means one digit after the comma. So the 1050 MB image will show as 1.1 GB.

**Describe alternatives you've considered**
Alternatively round to the nearest GB, that will still show a size jump later.

**Additional context**
Here we see a big jump in image size between 2.0.2 and 2.1.0 when in reality the increase was much smaller
![registry](https://user-images.githubusercontent.com/2501617/200835955-a304e4a3-09bc-4c9b-9dfc-082277023395.png)

**Comment by Joxit** [comment]
Hi, thank you for using my project and for your feature request :smile: 

I added you in my contributor list https://github.com/Joxit/docker-registry-ui/blob/main/CONTRIBUTORS.md and this should by added in 2.3.3 :wink:

**Comment by MartinHerren** [comment]
Great, many thanks !
