### ISSUE TITLE
Add Title when using REGISTRY_URL (feature request)

### ISSUE THREAD

**Issue by soosap** [Joxit/docker-registry-ui#28]
Hi I have tested the app using the fix suggested by https://github.com/Joxit/docker-registry-ui/pull/27. First of all, I can confirm that the PR solves the problem.

Yet another small issue arises when using REGISTRY_URL: **No title is being set.**

<img width="515" alt="screen shot 2018-02-17 at 00 12 31" src="https://user-images.githubusercontent.com/7187705/36333465-5829a82a-1377-11e8-89df-a2cc651915a4.png">

Would it be possible to pass a custom name via an optional environment variable i.e. `REGISTRY_TITLE`?

Thanks for considering :)

**Comment by Joxit** [comment]
Done in #32 (v0.3.4)
Use `REGISTRY_TITLE` to set your custom title :smile: 
Thanks again ;)
