### ISSUE TITLE
Add pushed/uploaded time to the UI

### ISSUE THREAD

**Issue by MrNocTV** [Joxit/docker-registry-ui#281]
**Is your feature request related to a problem? Please describe.**
Creation time is the creation of the original image, not the pushed time of the image to the registry specified by `REGISTRY_URL`

<img width="1573" alt="Screen Shot 2023-01-11 at 10 30 15" src="https://user-images.githubusercontent.com/11014873/211711426-1943b40d-11b6-4707-82d4-2fb06b56226f.png">

**Describe the solution you'd like**
Please consider adding 1 more field to display the time when the image is uploaded to the configured docker registry.

**Comment by Joxit** [comment]
Hi, thank you for using my project and posting features requests.

Unfortunately, the [Docker Registry Server API](https://docs.docker.com/registry/spec/api/) does not allow to have the uploaded date, only the creation date of the image is available.

I will close this feature request and mark it as wontfix + Related to Docker Registry
