### ISSUE TITLE
multi-select delete functionality (feature request)

### ISSUE THREAD

**Issue by soosap** [Joxit/docker-registry-ui#29]
Hi there,

here is another feature I would love to see in the UI. What do you think about it?

![multi-select-delete](https://user-images.githubusercontent.com/7187705/36334137-84b5183a-137b-11e8-91bb-43c2cfba1bd7.png)

**Comment by RANGERBEE** [comment]
Plus please add the garbage collect activate button.  ;-)  thank you!!

**Comment by Joxit** [comment]
It's impossible to activate garbage collection by http request.
You must do it via the command line.
You should add a cron or something like this to garbage collect old images every week for exemple

**Comment by Joxit** [comment]
Release in [1.2.0](https://github.com/Joxit/docker-registry-ui/releases/tag/1.2.0)
