### ISSUE TITLE
Multilevel branching of the repository

### ISSUE THREAD

**Issue by mexaniksmirnov** [Joxit/docker-registry-ui#293]
Hi!
Is it possible to implement the ability to branch directories in a repository with the union of identical directories. Now the branching is implemented by level 1, all subsequent repository directories are not merged.

**Comment by Joxit** [comment]
Hi, thank you for using my project.

So your idea i having something like this ? (this is a mock)
![2023-04-14_05-49](https://user-images.githubusercontent.com/5153882/231936952-f0dad603-6434-40c4-b56e-e19694ac2045.png)

With infinite branching ? Or a configuration and you setup a min-max ? Or just add a new level ?

**Comment by mexaniksmirnov** [comment]
> Hi, thank you for using my project.
> 
> So your idea i having something like this ? (this is a mock) ![2023-04-14_05-49](https://user-images.githubusercontent.com/5153882/231936952-f0dad603-6434-40c4-b56e-e19694ac2045.png)
> 
> With infinite branching ? Or a configuration and you setup a min-max ? Or just add a new level ?

Hello! Thanks for the answer! What I see on the screen is quite enough, but it is better, of course, that the number of levels is the maximum possible 5. This will be much better visually perceived.
