### ISSUE TITLE
Reverse default sort order of images tags

### ISSUE THREAD

**Issue by ArwynFr** [Joxit/docker-registry-ui#294]
By default, tags are sorted by creation date, as stated on #45 
However they are sorted in ascending order, so latest image is at the bottom of the page.
I think it would be better the other way around.

**Comment by Joxit** [comment]
Hi, thank you for using my project and posting feature requests :smile:
This is a simple and nice idea, I will take care of it and add a new configuration `DEFAULT_TAG_ORDER` :+1:
