### ISSUE TITLE
2.1.0升级2.4.1后GET /v2/<name>/manifests/<reference>接口提示cors

### ISSUE THREAD

**Issue by Lce-Lemon** [Joxit/docker-registry-ui#295]
Hi, I use this docker registry UI and I have an issue...

## Bug description
2.1.0升级2.4.1后```GET /v2/<name>/manifests/<reference>```接口提示cors
对比两个请求发现请求头的Accept多了两个
一个是application/vnd.oci.image.indes.v1+json
另外一个是application/vnd.docker.distribution.manifest.list.v2+json

**Comment by Joxit** [comment]
Hi, thank you for using my project :smile: 

Sorry I accept only issues in English.
