### ISSUE TITLE
display image size (feature request)

### ISSUE THREAD

**Issue by soosap** [Joxit/docker-registry-ui#30]
Hi there,

this is my third and last suggestion on what would add a lot of value to the project, displaying image size. I leave this here for discussion :)

![size-property](https://user-images.githubusercontent.com/7187705/36334589-7be60132-137c-11e8-9b4d-fbc65b95d80f.png)

**Comment by Joxit** [comment]
Thanks for your feature requests :smiley: 
Work in Progress, I will merge ASAP :wink:
