### ISSUE TITLE
Keep repository entry expanded.

### ISSUE THREAD

**Issue by logopk** [Joxit/docker-registry-ui#302]
**Is your feature request related to a problem? Please describe.**
Is there a way to keep current repository entry expanded? 
When navigating back from an image, I would like to have the parent entry expanded.

I have only one repository, so this would be neat.

Thank you.

**Comment by logopk** [comment]
That would be absolutely perfect!
Thanks!

**Comment by Joxit** [comment]
Hi there, I added `CATALOG_DEFAULT_EXPANDED` option that will be available in [2.5.0](https://github.com/Joxit/docker-registry-ui/milestone/6) and is already available in `main` tag.

The default value is `true` when there is only one repository and `false` otherwise.
