### ISSUE TITLE
Docker Registry >=2.8 sets catalog max entries to 1000

### ISSUE THREAD

**Issue by HighOnMikey** [Joxit/docker-registry-ui#306]
For anyone using Docker Registry >=2.8: You need to either change the configuration of the Docker Registry or the UI, as the Docker Registry now defaults the maximum entries per page to 1000.

This Docker Registry configuration option does not appear to be documented in the registry repo or [docs.docker.com/registry](https://docs.docker.com/registry/configuration/).

You will see this error from the registry: 
**Code**: `PAGINATION_NUMBER_INVALID`
**Message**: `invalid number of results requested`
**Detail**: `n: 100000`

### Option 1a: YAML config

**`/etc/docker/registry/config.yml`**
```yaml
# ...
catalog:
  maxentries: 100000
# ...
```

reference: 
https://github.com/distribution/distribution/blob/f7717b7855ca44bef5b8ccb293927a83c1d68600/configuration/configuration.go#L271

### Option 1b: Environment variable
`REGISTRY_CATALOG_MAXENTRIES=100000`

reference:
https://docs.docker.com/registry/configuration/#override-specific-configuration-options

### Environment variable
`CATALOG_ELEMENTS_LIMIT=1000`

reference:
https://github.com/Joxit/docker-registry-ui/blob/ba322e076ff97fcb326775bea2a0f80c3387b063/README.md?plain=1#L86

#### Change Hard-coded default

Set to `1000`:
https://github.com/Joxit/docker-registry-ui/blob/ba322e076ff97fcb326775bea2a0f80c3387b063/src/components/docker-registry-ui.riot#L169

**Comment by Joxit** [comment]
Hi, thank you for using my project and posting issues! 🥰

Thanks for this information, I will reduce the catalog element limit in the next release and add your information about the registry configuration!

**Comment by QuentinBellus** [comment]
Thank you so much for this, CATALOG_ELEMENTS_LIMIT did the trick, until this is fixed in the next release.

**Comment by Joxit** [comment]
Hi there ! The fix has bee published ! You can use the tag `main` or wait until I publish the next version [2.5.0](https://github.com/Joxit/docker-registry-ui/milestone/6) (I still have some stuff to do)

I've included some error message too for this particular use case :wink:
