### ISSUE TITLE
Circular dependency when running locally

### ISSUE THREAD

**Issue by Vulwsztyn** [Joxit/docker-registry-ui#313]
Hi, I tried to run dev version of the registry ui and got circural dep.

## Bug description
```
(!) Circular dependency
src/components/tag-list/tag-table.riot -> src/components/tag-list/remove-image.riot -> src/components/tag-list/tag-table.riot
```
## How to Reproduce

For UI bug, steps to reproduce the behavior:
1. Run `npm install`
2. Run `npm start`

**Comment by Joxit** [comment]
Hi that you for using my project 😊
This is not a bug but a warning

**Comment by Vulwsztyn** [comment]
Thx, I'm apparently dumb and thought that the server is not running
