### ISSUE TITLE
Shift-click for multi-delete-in-a-row selects wrong images when using non-default sorting

### ISSUE THREAD

**Issue by attackercan** [Joxit/docker-registry-ui#323]
Hi!

## How to Reproduce

I use this docker registry UI 2.6.0, and it fails to multi-delete images with non-default sorting

1. Open any container with many tags
2. Change default sorting to "By creation date, asc"
3. Shift-click on any sequential images
4. See that Docker registry UI also selected images that I didn't chose to select

## Expected behavior

It only selects sequential images

## Screenshots

![image](https://github.com/Joxit/docker-registry-ui/assets/17142772/e6638670-3df6-4ce0-8fde-5fd4c5aba725)

## System information

- OS: Mac OS M2
- Browser: Firefox 114.0.2 (64-bit)

**Comment by Joxit** [comment]
Hi, thank you for using my project and submitting issues 😊

Bug confirmed, I will try to fix it!

**Comment by Joxit** [comment]
Hi, this should be fixed in [v2.5.1](https://github.com/Joxit/docker-registry-ui/releases/tag/2.5.1)
