### ISSUE TITLE
Deleting for multiple selected tags works strangely

### ISSUE THREAD

**Issue by onlyfanfuriks** [Joxit/docker-registry-ui#332]
In my repository I have 2 types of tags 1. `tagname-...-dev` and 2. `vA.B.C` when I try to delete selected tags of type 1. I will get the error message "MANIFEST_UNKNOWN", but the tags will be deleted, and sometimes this leads to the deletion of the second type of tags. Is this an error or does it depend on whether my type 1 and type 2 tags use the same cached layers, and deleting one tag with a shared layer will delete the unselected tag depending on this layer?

**Comment by onlyfanfuriks** [comment]
Sometimes the same problem occurs when I delete tags using the `/v2` API, and some tags that I did not request to delete will also be deleted.

**Comment by Joxit** [comment]
Hi, thank you for using my project and posting issues :smile: 

Is your question related to the [FAQ](https://github.com/Joxit/docker-registry-ui#faq) question:
> * Why when I delete one tag, all tags with the same SHA are deleted ?
>   * This a docker registry API limitation, there is only one way to [delete images with tag](https://docs.docker.com/registry/spec/api/#deleting-an-image), it's by its name and its manifest (it's a sha of the content). So when you delete a tag, this will delete all tags of this image with the same SHA/manifest.

When you delete two images with the same SHA, it will send two requests to the registry, the first one will succeed and the second one fail with 404 `MANIFEST_UNKNOWN`.

**Comment by onlyfanfuriks** [comment]
Thanks! that solved my question
