### ISSUE TITLE
[Select/Deselect  All] buttin

### ISSUE THREAD

**Issue by kevinblo** [Joxit/docker-registry-ui#335]
Thank you for your excellent project. Could you please add a "select/deselect all" button? I had to delete several dozens of images, it was long :)

**Comment by Joxit** [comment]
Hi there, thank you for using my project.
Is your feature request linked to the second point (added in 1.2.1) in the [README.md#hidden-features](https://github.com/Joxit/docker-registry-ui#hidden-features) section ?

> * Many ways to delete multiple images at once
>   * Select multiple tags to delete with checkboxes (see https://github.com/Joxit/docker-registry-ui/issues/29 and https://github.com/Joxit/docker-registry-ui/pull/79). Since 1.2.0
>   * Select all tags of the page with ALT + Click on the indeterminate checkbox (see https://github.com/Joxit/docker-registry-ui/issues/80 and https://github.com/Joxit/docker-registry-ui/pull/81). Since 1.2.1
>   * Select all contigous tags between two tags with Shift + Click on the first tag then Shift + Click on the second tag (see https://github.com/Joxit/docker-registry-ui/pull/287). Since 2.4.0

**Comment by kevinblo** [comment]
Thank you
