### ISSUE TITLE
Support for arm image

### ISSUE THREAD

**Issue by jacen92** [Joxit/docker-registry-ui#34]
Hi,

I would like to have a raspberryPi (arm32v6 and/or arm32v7) compatible image.
Is it possible?

Thanks

**Comment by Joxit** [comment]
Hi,

Yes it's now possible ! You can pull the image joxit/docker-registry-ui:arm32v7 on your Raspberry Pi !

Thank you for your feedback :smile:

**Comment by jacen92** [comment]
Thank you, the arm32v7-static image works on my raspberry Pi (but arm32v7 does not work)

And thanks for this project

**Comment by Joxit** [comment]
That's strange, it's based on the same docker image and it works on my Raspberry :/

You are welcome, it's a pleasure :smile: 

You can close the issue if all is good.

**Comment by jacen92** [comment]
All's good thanks
