### ISSUE TITLE
Refused to get unsafe header "Docker-Content-Digest"

### ISSUE THREAD

**Issue by lkinsella** [Joxit/docker-registry-ui#347]
This is a confusing one for me, I've set up the UI and it's working and talking to my Docker Registry, however I keep getting these errors:

![image](https://github.com/Joxit/docker-registry-ui/assets/605446/d8731fe8-d9fd-4b23-bac2-1bca57a28421)

However where I'm stuck is the `Access-Control-Expose-Headers` header _is_ set like this:

![image](https://github.com/Joxit/docker-registry-ui/assets/605446/08a6b7e0-adcd-490f-b458-f898282adb89)

So why can't it access the header? What am I missing?

**Comment by Joxit** [comment]
Hello,
Please the next time use the templates I made will all the fields completed.

Except this message, is something missing in the UI or everything is working fine ?
