### ISSUE TITLE
Unable to pass parameters via url to implement basic authentication in docker registry UI 

### ISSUE THREAD

**Issue by Pumbaa-peng** [Joxit/docker-registry-ui#348]
Hi, I use this docker registry UI and I have an issue...

## Bug description
I'm using http://registry:ui@server_ip:80 to access the docker registry UI, but it's still asking me for a user password.
## How to Reproduce

For UI bug, steps to reproduce the behavior:

For service bug, steps to reproduce the behavior:

My docker-compose file
```yml

```

My private docker registry configuration
```yml

```

## System information

- OS: [e.g. Debian, Windows, Mac OS, Android 9...]
- Browser:
    - Name: [e.g. Chrome, Firefox...]
    - Version: [e.g. 114.0.5735.198, 102.11.0...]
- Docker registry UI:
    - Version: [e.g. 2.5.0, 2.6.0-84b31f2cfb...]
    - Server: [docker or dist]
    - Docker version: [e.g. 24.0.4...]
    - Docker registry ui tag: [latest, main, 2.5.0, 2...]
    - OS/Arch: [e.g. linux/amd64]
    - Tools: [e.g. docker-compose, kubernetes, electron..]

**Comment by Joxit** [comment]
Hi,
Thanks for using my project.

The basic auth via URL is giving the information to the user interface.
The secured part is your registry server and not the user interface.

If using a password bothers you, you can add update your configuration (see https://github.com/Joxit/docker-registry-ui#available-options) set the basic auth url here `REGISTRY_URL` or use `NGINX_PROXY_PASS_URL` with `NGINX_PROXY_HEADER_*`

The last option is deploy with SINGLE_REGISTRY=false and use the url query parameter with your password or use the demo `https://joxit.dev/docker-registry-ui/demo/?url=https://registry:ui@ip/` for both solutions, you just need to bookmark the url and voilà.

If you need more info, please complete correctly your issue with asked questions
