### ISSUE TITLE
Search bar "placeholder" has low contrast on dark mode

### ISSUE THREAD

**Issue by silverwind** [Joxit/docker-registry-ui#357]
## Bug description

The text here has very low contrast ratio of 1.35:

<img width="249" alt="image" src="https://github.com/Joxit/docker-registry-ui/assets/115237/d78e7c32-307b-4b83-9293-2a519fdfcba4">

## How to Reproduce

Open UI, set dark mode

## Expected behavior

A contrast ratio of at least 4.5 to pass [WCAG AA](https://webaim.org/resources/contrastchecker/):

<img width="870" alt="image" src="https://github.com/Joxit/docker-registry-ui/assets/115237/efeb9308-4852-4123-b74d-006cb66e72b3">

**Comment by lukengda** [comment]
i've made some tweaks for my setup. I will provide a PR showing off the minimal theme changes, maybe they can get pulled in as they are or with more refinement.
