### ISSUE TITLE
support pagination

### ISSUE THREAD

**Issue by madhukar93** [Joxit/docker-registry-ui#36]
I can just see the first page of the catalog, it can be quite misleading.
href for the next page seems to come as the `Link` header

**Comment by gionn** [comment]
> There is no pagination with my UI for now. This should show all your images.
> How many images have you on your registry?

I have ~30 images, but thousands of tags for some of them, making browser unusable while navigating it.

**Comment by Joxit** [comment]
Ouch, that's huge.... And this cause a lot of call to you registry.... :thinking: 

I thought of something else, an infinite scroll instead of pagination. But you will also need a search bar I guess for your tags ?

**Comment by gionn** [comment]
a search bar with support for regexp would have solved my today problem (that I solved making a script using [reg](https://github.com/genuinetools/reg)

I am not a fan of infinite scrolling since I cannot jump easily at the end of the list.

**Comment by Joxit** [comment]
Hum... OK, I will think about it

**Comment by Joxit** [comment]
This has been released in v1.3.0 ! :tada:
