### ISSUE TITLE
docker-registry-ui.js:40 Uncaught TypeError: Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by iDmple** [Joxit/docker-registry-ui#372]
Hi, I use this docker registry UI (chart helm) with a private registry deployed separately.

## Bug description
I have an issue with the Creation Date not displaying for OCI charts only (in case of docker images it works fine).
My registry does send the creation date and I can see it when accessing the URL with curl for OCI charts.

## How to Reproduce
Push an OCI chart to a private registry. 

For UI bug, steps to reproduce the behavior:
1. Click on an image
2. See creation is shown as 'ago' only with this bug in the console:
<img width="1496" alt="Screenshot 2024-04-10 at 14 53 50" src="https://github.com/Joxit/docker-registry-ui/assets/5065505/d137a68d-bcc3-45b5-af4e-d8262f68b8e1">

## Expected behavior

I want to be able to see the creation date.

## System information

- OS: MacOS Sonoma
- Browser:
    - Name: Chrome
    - Version: 123.0.6312.107
- Docker registry UI:
    - Version: 1.1.3
    - Server: k8s as a service with helm chart
    - Docker version: -
    - Docker registry ui tag: 1.1.3
    - OS/Arch: linux/amd64
    - Tools: kubernetes

**Comment by Joxit** [comment]
Hello, sorry for the late response.

Could you tell me how did you create the OCI chart ?

FYI, I'm trying to support OCI stuff, but the project is meant to be used for docker images.

**Comment by iDmple** [comment]
Np. I created it with `helm create`. Let me know if you need any other info!

**Comment by Joxit** [comment]
Could you tell me the full process will all the options used ? From the creation until the push to the private registry ?
I have never used it :sweat_smile:

**Comment by Joxit** [comment]
Hello, I came up with a fix and feature, could you try the tag `joxit/docker-registry-ui:main` and tell me if everything is okay now ?

You may access to the "history" too 
![image](https://github.com/user-attachments/assets/8b011c14-7c5b-4f40-9b0c-49fed1db035c)
