### ISSUE TITLE
Hello, I'd like to know why adding new HTML under /dist doesn't recognize custom components like index.html.

### ISSUE THREAD

**Issue by yanyan129** [Joxit/docker-registry-ui#388]
Hi, I use this docker registry UI and I have an issue...

## Bug description
Hello, I'd like to know why adding new HTML under /dist doesn't recognize custom components like index.html.

## How to Reproduce
For service bug, steps to reproduce the behavior:
I want to turn index.html into a selection page where choosing different options leads to different html pages.
These html pages will display previously created html pages.

**Comment by Joxit** [comment]
Hi, thank you for using my project.
Unfortunately your question is outside the scope. The docker registry UI is a standalone project.
