### ISSUE TITLE
`v2/_category` is short.

### ISSUE THREAD

**Issue by Ohen** [Joxit/docker-registry-ui#39]
I have a so many images but it is only use `v2/_category`, I can not bring a list of all our images. If you change `v2 / _category?n=100000` instead of `v2 / _category` we will see more images.

![image](https://user-images.githubusercontent.com/10244446/41143787-9bfbfaf6-6b35-11e8-8977-89020f8231a4.png)

**Comment by Joxit** [comment]
Hi.
Thank you for your issue.
How many images have you on your registry? +100 ? +1k ? +10k? +100k? (for my tests)

I will try your hot fix for now. I hope that will solve your issue.

**Comment by Ohen** [comment]
our registry had maybe more 100k. I solved via this changes. thanks

**Comment by Joxit** [comment]
Oki, that's cool then :)
