### ISSUE TITLE
Specifying a subfolder path for docker-registry-ui to serve on?

### ISSUE THREAD

**Issue by iyxan23** [Joxit/docker-registry-ui#390]
**Is your feature request related to a problem? Please describe.**
I have my own nginx running on the host and I would like to have `docker-registry-ui` to run under a subfolder path so it wouldn't interfere with my already preoccuiped `/` path.

**Describe the solution you'd like**
A simple `NGINX_SERVE_URL` env or something that sets the `location /(..here..)` would be nice!

**Describe alternatives you've considered**
I tried doing an nginx `rewrite` on my host but doesn't seem to work well with this specific container.

**Additional context**
I'll try to hit up a PR once you agreed to the idea 😉

**Comment by Joxit** [comment]
Hello, thank you for using my project and submitting issues.

Did you try this

https://github.com/Joxit/docker-registry-ui/blob/b7f732a60671cebe5716ef9f21af0bf8c1d036be/examples/token-auth-keycloak/conf/proxy/nginx.conf#L73-L76

I'm also using this configuration on one of my servers
```
  location /ui/ {
    proxy_pass http://docker-registry-ui/;
  }
```

**Comment by iyxan23** [comment]
> Hello, thank you for using my project and submitting issues.
> 
> Did you try this
> 
> https://github.com/Joxit/docker-registry-ui/blob/b7f732a60671cebe5716ef9f21af0bf8c1d036be/examples/token-auth-keycloak/conf/proxy/nginx.conf#L73-L76
> 
> I'm also using this configuration on one of my servers
> 
> ```
>   location /ui/ {
>     proxy_pass http://docker-registry-ui/;
>   }
> ```

thank you for the reply! unfortunately I had already deleted the project I was working on, so I'm unable to test your suggestion.

Closing this issue for now as resolved :smile:

**Comment by nitram2342** [comment]
I tried this and it does not work, because the application returns HTML with links/paths without the /ui prefix. So the browser cannot handle this. I think, it needs a PATH_PREFIX or something like that. At least it would be useful for handling multiple applications on the same vhost.

**Comment by Joxit** [comment]
I'm using relative path, as long as the url of the UI has a leading slash, the browser will send requests in the same folder to the UI... Then it's only a matter of configuration of your reverse proxy. 
There are 90% of chance that you could configure it without a path prefix.

**Comment by nitram2342** [comment]
Thanks a lot for your explanation. I missed the part with the relative path.
