### ISSUE TITLE
Issue with deleting tag when other tag of the same image exists

### ISSUE THREAD

**Issue by PavelD** [Joxit/docker-registry-ui#399]
Hi, I use this docker registry UI and I have an issue...

## Bug description
I pushed single image into registry 3 times:

* registry.mydomain.duckdns.org/new-eclipse-mosquitto:latest
* registry.mydomain.duckdns.org/eclipse-mosquitto:latest
* registry.mydomain.duckdns.org/eclipse-mosquitto:new

When I want to delete registry.mydomain.duckdns.org/eclipse-mosquitto:latest or registry.mydomain.duckdns.org/eclipse-mosquitto:new both tags are removed.

The image registry.mydomain.duckdns.org/new-eclipse-mosquitto:latest is not impacted (i.e. not removed).
## How to Reproduce

Upload single image with 2 names and 3 tags.

For UI bug, steps to reproduce the behavior:
1. Go to image detail, whee is list of images available
2. Select one of the duplicated image. the second keep not selected.
3. Click on delete icon in the header in the beginning of the page
4. The pop-up shows you are about to delete both tags
5. when click on DELETE button both images are deleted.

## Expected behavior

Only one tag is removed.

## System information

- OS: amd64 linux
- Browser:
    - Name: Firefox
    - Version: 128.3.1esr (64-bit)
- Docker registry UI:
    - Version: 2.6.0-b7f732a606
    - Server: docker
    - Docker version: 20.10.21 (docker registry image: registry:2)
    - Docker registry ui tag: latest
    - OS/Arch: linux/amd64
    - Tools: portainer

**Comment by Joxit** [comment]
Hi,

Please read the [FAQ](https://github.com/Joxit/docker-registry-ui?tab=readme-ov-file#faq)
> - Why when I delete one tag, all tags with the same SHA are deleted ?
>   - This a docker registry API limitation, there is only one way to delete images with tag, it's by its name and its manifest (it's a sha of the content). So when you delete a tag, this will delete all tags of this image with the same SHA/manifest.
