### ISSUE TITLE
Cross Site Request to Registry blocked by Browser

### ISSUE THREAD

**Issue by Xnyle** [Joxit/docker-registry-ui#55]
I deployed joxit/docker-registry-ui:arm64v8 via k8s, all went well, but after I add a registry I get the following warning as a popup on the bottom:

> An error occured: Check your connection and your registry must have `Access-Control-Allow-Origin` header set to `http://192.168.126.3`

The frontend is opening http://192.168.126.2:5000/v2/_catalog?n=100000 but this request is blocked.

When opening the url in a new tab I get a response:

`{
"repositories": [
"helloworld"
]
}`

So registry and registry ui are working, I just don't know how to get it working without DNS entries?

Any suggestions?

**Comment by Xnyle** [comment]
Yeah, sorry, read over that part a few times cause I thought that was only Docker Compose config stuff.
Just figured out that you have to put that "stuff" in an envFrom.configMapRef with k8s.
Steep learning curve figuring out what all those container lego pieces do.

**Comment by Xnyle** [comment]
Yeah thanks that's working now, the doc about URL and REGISTRY_URL could be less misleading though.

**Comment by Joxit** [comment]
Ok, thank you :smile: 
I will try to update the doc so
