### ISSUE TITLE
Development Issue while trying to display a new page with router

### ISSUE THREAD

**Issue by lennartblom** [Joxit/docker-registry-ui#57]
Hi there!
First of all: Thank you very much for providing such a nice simple docker-registry-ui. We ware really happy to have your application up and running in our team for our private company registry.

I am currently working on a feature displaying the image tag's history (that the content you are getting at the REST endpoint 

![screen shot 2018-12-01 at 11 50 50](https://user-images.githubusercontent.com/4670057/49327278-ddff6280-f55f-11e8-8c3b-0f4243df8a1c.jpg)

The progress  I did so far is quite nice, but I stuck at using your application's router...

**I created the following elements for navigating to a new page:**

1. Define a suitable `go` function

```
registryUI.taghistory.go = function (image, tag) {
    route('taglist/joxit/docker-registry-ui');
};
```
2. Implement an entry in the app.tag `<main>` section

```
<tag-history if="{route.routeName == 'taghistory'}"></tag-history>
```

3. Programm the route function:

```
route('/taghistory/image/*/tag/*', function (image, tag) {
    console.log("Welcome to the tag history");
    console.log("Image='" + image + "' with tag='" + tag + "'");
    route.routeName = 'taghistory';

    registryUI.taghistory.image = image;
    registryUI.taghistory.tag = tag;

    if (registryUI.taghistory.display){
        console.log("Displaying Tag History");
        registryUI.taghistory.loadend = false;
        registryUI.taghistory.display();
    }
    registryUI.appTag.update();
});
```

I  commited and pushed my code [right here](https://github.com/lennartblom/docker-registry-ui) and I'd be totally thankful if you give me a hint why the navigation does not work. From my point of view there is no obvious difference  between my implementation and the **change from catalog-view to taglist-view**.

Thank you in advance! And thanks again for your great work! 👍

Cheers from Germany,
Lennart

**Comment by lennartblom** [comment]
Thanks for your quick feedback!

Sorry, about the indentation... I will configure my code formatter right!

But the scene of HBO's Silicon Valley I have to share, I guess! 😛 
https://www.youtube.com/watch?v=SsoOG6ZeyUI

**Comment by Joxit** [comment]
You are welcome :wink: 

Okay, thank you :smile: 
Ha ha ha ha great, that's funny :rofl:
