### ISSUE TITLE
REGISTRY_URL with https

### ISSUE THREAD

**Issue by gesof** [Joxit/docker-registry-ui#62]
`docker run -d -p 8000:80 -e URL=https://somedomain.com:5000 -e DELETE_IMAGES=true joxit/docker-registry-ui:static`

results in: 

`<!DOCTYPE html> <html> <head> <title>Error</title> <style> body { width: 35em; margin: 0 auto; font-family: Tahoma, Verdana, Arial, sans-serif; } </style> </head> <body> <h1>An error occurred.</h1> <p>Sorry, the page you are looking for is currently unavailable.<br/> Please try again later.</p> <p>If you are the system administrator of this resource then you should check the error log for details.</p> <p><em>Faithfully yours, nginx.</em></p> </body> </html>`

Log:

`[error] 13#13: *10 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: 44.33.22.11, server: localhost, request: "GET /v2/_catalog?n=100000 HTTP/1.1", upstream: "https://11.22.33.44:5000/v2/_catalog?n=100000"`

**Comment by Joxit** [comment]
Hello,

The `URL` environment will result to an XHR request from your browser to your registry URL (here it's `https://somedomain.com:5000`). In that case, it's an error on your private registry.

**Comment by Joxit** [comment]
Closed due to inactivity.
