### ISSUE TITLE
set proxy_ssl_server_name on

### ISSUE THREAD

**Issue by rucciva** [Joxit/docker-registry-ui#70]
Hi! first of all, thanks for open sourcing this great project.

I have a problem connecting it with My registry that is behind caddy https reverse proxy which handles multi domain.  The error happens when tls handshake is being made
` http: TLS handshake error from 172.19.0.2:56438: no certificate available for ''`.
It seems that no SNI extension are sent to the registry. I figure out that adding 
`proxy_ssl_server_name on` in the [nginx config](https://github.com/Joxit/docker-registry-ui/blob/master/nginx/default.conf#L13) will fix this issue

**Comment by Joxit** [comment]
Hi! I am happy that you like my project.

That's strange, I don't have this issue with a registry over https.
Are you using the option `REGISTRY_URL` ? I have a concrete example with https : `REGISTRY_URL=https://raw.githubusercontent.comoxit/docker-registry-ui/master/demo/v2` (this is a mocked registry).

If both your UI and registry are in the same docker network, you don't need an https connection.
Are you using the correct domain name or an IP?

**Comment by rucciva** [comment]
> Are you using the option `REGISTRY_URL` ?
yes i am.

> If both your UI and registry are in the same docker network
Unfortunately it's not, it's on a different machine.

> I have a concrete example with https : `REGISTRY_URL=https://raw.githubusercontent.comoxit/docker-registry-ui/master/demo/v2` (this is a mocked registry).
i think my registry is behind https reverse proxy that has strict SNI checking. When i encounter this problem, i have come to this [discussion](https://www.ruby-forum.com/t/proxy-pass-not-seen-as-sni-client-according-to-apache-directive/244065/5) and tried the solution and it works.

**Comment by Joxit** [comment]
Oh, well then. I will add this option.

Thank you very much for your report. :)
