### ISSUE TITLE
no-auth description error in readme

### ISSUE THREAD

**Issue by glebsts** [Joxit/docker-registry-ui#72]
Hello,
Thank you for your tool!
README contains following:

> If your docker registry does not need credentials, you will need to send this HEADER:
> `Access-Control-Allow-Origin: '*'`

But that leads to `line 16: cannot unmarshal !!str `*` into []string`, because this parameter is expected to be an array. Later you have valid example of `Access-Control-Allow-Origin: ['http://127.0.0.1:8001']`
So it must be 
`Access-Control-Allow-Origin: ['*']`
At least that worked for me.

**Comment by Joxit** [comment]
Hello,
Thank you for your issue, I will fix this :smile:
