### ISSUE TITLE
Multi-select delete with select all

### ISSUE THREAD

**Issue by gionn** [Joxit/docker-registry-ui#80]
Hi,

it would be great to have the possibility to select all images in the current view in order to speed-up the deletion of many tags.

**Comment by Joxit** [comment]
Hello,
thank you for your issue, I don't know how I will integrate this feature with the current UI... (Maybe a trick ? Such as ALT + click when no tags are selected ?)

**Comment by gionn** [comment]
I was hoping that clicking on the table column could have selected all the entries, but currently it deactivate the multi-select feature :)

using a shortcut can be a good idea, just add an hint somewhere to let users discover it.

Thanks!

**Comment by Joxit** [comment]
Yes, this was my workflow, click the button for activate/deactivate multi-select and when one tag is selected, the button is changed in a trash for delete all selected elements.
With this workflow the ui is still clean and simple.

Okay, I will do it ASAP, thx for your feedback 😉
