### ISSUE TITLE
Indent aggregated entries after expansion

### ISSUE THREAD

**Issue by Jauler** [Joxit/docker-registry-ui#90]
Hi,

I quickly searched for similar issue, but did not find anything.

I just thought, that it would be a lot clearer to indent aggregated entries, so that after expanding it would look somewhat like this:
```
aggregated/
        aggregated/image1
        aggregated/image2
        .....
```

Instead of 
```
aggregated/
aggregated/image1
aggregated/image2
.....
```

**Comment by Joxit** [comment]
Hello,

thank you for your issue, this has been done in eec736d.
I think I will do a release now :)

**Comment by Jauler** [comment]
Wow, that was fast :)
