### ISSUE TITLE
Delete an entire image from the registry

### ISSUE THREAD

**Issue by zedtux** [Joxit/docker-registry-ui#93]
I'm missing a button to delete the entire `library/redis` image for instance.

**Comment by Joxit** [comment]
Hello :)
This can't be done with the registry API https://github.com/Joxit/docker-registry-ui/issues/53#issuecomment-441320532.
You will need to delete the folder manually because even if you delete all tags, the repository will still be present.

**Comment by zedtux** [comment]
Thank you @Joxit for your answer.
