### ISSUE TITLE
Can't delete image

### ISSUE THREAD

**Issue by vitobotta** [Joxit/docker-registry-ui#94]
Hi! I just installed the UI in Kubernetes using the Helm chart, and I can't delete images. The message `{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}` is shown when I try to delete an image. What can it be? Thanks!

**Comment by vitobotta** [comment]
Nevermind, it was a setting on the registry itself. I had to add the following to the config map

```
storage:
  delete:
    enabled: true
```

**Comment by vitobotta** [comment]
Uhm actually it deleted the image from the UI now but it's still on disk?

**Comment by vitobotta** [comment]
In case someone has the same issue, you need to perform garbage collection to actually clean up the blobs that can be deleted. Exec `sh` into the pod of the registry:

```
kubectl -n docker-registry exec -it docker-registry-* sh
```

Create a config file:

```
cat <<EOF > /tmp/config.yml
version: 0.1
storage:
  filesystem:
    rootdirectory: /var/lib/registry/
EOF
```

Run garbage collection:

```
bin/registry garbage-collect [--dry-run] /tmp/config.yml
```

This does the cleanup. I am still learning this stuff so I wasn't sure how the deletion worked. Thanks for the UI!

**Comment by Joxit** [comment]
Yes, that's it ! But this will not delete images without tags, see https://github.com/Joxit/docker-registry-ui/issues/53#issuecomment-441320532.

**Comment by vitobotta** [comment]
Hi @Joxit , weird behaviour imo. I wasn't expecting this from the docker stuff tbh

**Comment by Joxit** [comment]
Hi there, I created an official Helm chart for docker-registry-ui available here https://helm.joxit.dev/ with the source code [on github](https://github.com/Joxit/helm-charts). The Chart is compatible with the latest docker registry UI :smile:  (2.2.1)

Feel free to send me feedback if you try it.
