### ISSUE TITLE
Cannot run on Rpi3B+ aarch64

### ISSUE THREAD

**Issue by 121593** [Joxit/docker-registry-ui#95]
Hello,

I cannot manage to run the project on a Raspberry 3 B+ loaded with RancherOs.

The problem may lie in the architecture resolution : AFAIK arm64v8 images should run on aarch64 labelled architecture [[1]](https://unix.stackexchange.com/questions/477097/when-uname-reports-aarch64-instead-of-arm64v8-willl-docker-ce-still-pull-arm64v), but docker says 'platform unsupported'.

I don't have deep docker knowledge, but a [manifest](https://docs.docker.com/engine/reference/commandline/manifest/) may help resolution ?

`uname -a` :
>Linux rancher 4.14.114-rancheros-v8 #1 SMP PREEMPT Tue May 14 07:57:18 UTC 2019 aarch64 GNU/Linux

partial  `docker info` :

>Server Version: 18.06.3-ce
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: xx
 Is Manager: true
 ClusterID: xx
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.1.26
 Manager Addresses:
  192.168.1.26:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: a592beb5bc4c4092b1b1bac971afed27687340c5
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.114-rancheros-v8
Operating System: RancherOS v1.5.3
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 919MiB
Name: rancher
ID: xxx
Docker Root Dir: /mnt/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Live Restore Enabled: false

Thx !

**Comment by Joxit** [comment]
Which tag are you using ? 

All tags are here : https://hub.docker.com/r/joxit/docker-registry-ui/tags

arm64v8 based images can't be used on aarch64 ? Did you ever used a nginx based docker image on your aarch64 Rpi ?

**Comment by 121593** [comment]
I actually tried various tags in case I was misunderstanding their purpose, but was expecting _arm64v8-static_ to work.

I managed to run nginx on the Rpi with an image from [linuxserver/docker-nginx](https://github.com/linuxserver/docker-nginx), which makes use of Docker manifest : 

`docker manifest inspect linuxserver/nginx`
>{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1579,
         "digest": "sha256:14583e01e9210f0579c99db485ee13f9b423e92c2c2b86f76f7568731a0e380b",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1579,
         "digest": "sha256:fba6387e0a966386699f95bc6fdb2665fb2a65d2e356bc6f4f679777a3b1d242",
         "platform": {
            "architecture": "arm",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1579,
         "digest": "sha256:6d5442233ba76cf6036545c084804107fb1f687fd18eaf0a3552c174de6d4734",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      }
   ]
}

`docker image inspect linuxserver/nginx` [partial] :
>[
    {
        "Id": "sha256:40fcb8c3f98e21c8f9308250baf52e9aae61c50762a79802667dd1f49ad73394",
        "RepoTags": [
            "linuxserver/nginx:latest"
        ],
       .....
        "Architecture": "arm64",
        "Os": "linux",
        "Size": 169931024,
        "VirtualSize": 169931024,
        ....
    }
]

**Comment by Joxit** [comment]
Ok, thank you for your response.
Can you now tell me if the image [`arm64v8/nginx`](https://hub.docker.com/r/arm64v8/nginx) works on your device ?

**Comment by 121593** [comment]
Just tested, I does works

**Comment by Joxit** [comment]
Okay, that's a good news

[joxit/docker-registry-ui:arm64v8-static](https://github.com/Joxit/docker-registry-ui/blob/master/arm64v8-static.dockerfile) is based on arm64v8/nginx, so this should work too.
I launched a new build for this tag, can you pull again my image and test if it works again ?

**Comment by Joxit** [comment]
No responses, mark as closed

**Comment by mcaulifn** [comment]
I see the armv7 tag is marked as amd64
https://hub.docker.com/layers/joxit/docker-registry-ui/arm32v7/images/sha256-939fec39f9dd3828272ca4bf73be5a8c21c0d6177d44c182dbe8ed08eb2cfaa9?context=explore

**Comment by Joxit** [comment]
Yes, this is normal, when you build a docker on a specific architecture, it will add your architecture as metadata in the image. My images are build by docker hub, and their servers are based on amd64 so it adds amd64 as architecture...
If you check the base image in [Dockerfile](https://github.com/Joxit/docker-registry-ui/blob/master/arm32v7-static.dockerfile), it's [arm32v7/nginx](https://hub.docker.com/r/arm32v7/nginx/tags) and they are on the correct architecture.
