### ISSUE TITLE
Tag deletion not accurate enough

### ISSUE THREAD

**Issue by mperelmu** [Joxit/docker-registry-ui#96]
When deleting a tag of a multiple-tagged image, the image is entirely deleted with all associated tags.
This is unexpected.

**Comment by Joxit** [comment]
Hello, thank you for your issue.

This is sadly a docker registry API limitation, there is only one way to [delete images with tag](https://docs.docker.com/registry/spec/api/#deleting-an-image), it's by its `name` and its `manifest` (it's a sha of the content).

That means when you delete a tag, all tags of the same image with the same manifest/sha will be deleted... :disappointed:

**Comment by mperelmu** [comment]
ok you are right.
But in that case i think that the **UI should display image id for each tag** so that user can evaluate what will really be deleted. This could replace (or be in addition to) repository column name which is the same for all images whithin a given repository.

**Comment by Joxit** [comment]
When you hover the tag, the sha256 is shown.
The column could be a solution, the other solution may be implement #84 and in the dialog message I write all tags that will actually be deleted (or at least a warning) :thinking: 

I think the dialog message is the best way, it will be easier for you to see what's going on.

**Comment by mperelmu** [comment]
Show sha256 when hover the tag is not really usefull as we can not see all sha256 at the same time.
Why not a warning but this forces user to attempt a deletion for retrieving this information. 
It would be better to identify at the first sight which tags refer to the same image.
Use same font colour for same sha256 (and sort list by sha256 to allow reuse of colours cyclically) could provide a good UX according to me.

**Comment by Joxit** [comment]
Hum.. Okay

> Use same font colour for same sha256 (and sort list by sha256 to allow reuse of colours cyclically) could provide a good UX according to me.

Thanks for the idea. I will apply this only when the sha256 is used by two ore more tags.
One page can have up to 100 tags and colors will not be relevant if there is no duplicate sha256.

**Comment by mperelmu** [comment]
i go on thinking about it. 
you are right that colours may be confusing.
What about that:
When you hover the tag (or the dustbin) , every line sharing the same sha256 are highlighted (colored or italic or bold or tabulated) ?

**Comment by Joxit** [comment]
Yes, but this will not help you if you have more than 15 tags and your view can only hold 10 tags. Because when you want to see all other tags, you will leave the hover mode.

What I can do is when you select a simple tag to delete, this will select also all tags with the same sha256. :thinking:

**Comment by mperelmu** [comment]
yes good idea !
